import { AnimatePresence, motion } from 'framer-motion';
import { Ban, ChevronLeft, ChevronRight, Gift, Loader2, Plus, RefreshCw, Search, Trash2, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import DashboardHeader from '../../components/dashboard/DashboardHeader';
import { createGiftCard, deactivateGiftCard, deleteGiftCard, getGiftCards } from '../../services/adminApi';

const PAGE_SIZE = 8;
const documentId = (value) => value?.$oid || value || '';
const money = (value) => new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT', maximumFractionDigits: 2 }).format(Number(value || 0));
const date = (value) => value ? new Intl.DateTimeFormat('en-BD', { dateStyle: 'medium' }).format(new Date(value)) : 'Not available';

export default function AdminGiftCards() {
  const [cards, setCards] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [reloadKey, setReloadKey] = useState(0);
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [creating, setCreating] = useState(false);
  const [confirmation, setConfirmation] = useState(null);
  const [busyId, setBusyId] = useState('');

  useEffect(() => {
    let active = true; setLoading(true); setError('');
    getGiftCards().then((response) => { if (active) setCards(response.data.data || []); })
      .catch((requestError) => { if (active) setError(requestError.response?.data?.message || 'Unable to load gift cards.'); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [reloadKey]);

  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return cards.filter((card) => !query || [card.code, card.value, card.status].join(' ').toLowerCase().includes(query)); }, [cards, search]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  useEffect(() => setPage(1), [search]);
  useEffect(() => setPage((current) => Math.min(current, totalPages)), [totalPages]);

  async function confirmAction() {
    const card = confirmation?.card; const id = documentId(card?._id); if (!id || busyId) return; setBusyId(id);
    try {
      if (confirmation.type === 'delete') { await deleteGiftCard(id); setCards((current) => current.filter((item) => documentId(item._id) !== id)); toast.success('Gift card deleted successfully.'); }
      else { const response = await deactivateGiftCard(id); setCards((current) => current.map((item) => documentId(item._id) === id ? response.data.data : item)); toast.success('Gift card deactivated successfully.'); }
      setConfirmation(null);
    } catch (requestError) { toast.error(requestError.response?.data?.message || 'Unable to update this gift card.'); }
    finally { setBusyId(''); }
  }

  return <div className="mx-auto max-w-[1400px] space-y-8">
    <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><DashboardHeader title="Gift Cards" description="Create and manage HomeBite gift card balances."/><motion.button whileHover={{ y: -2 }} whileTap={{ scale: 0.97 }} type="button" onClick={() => setCreating(true)} className="inline-flex w-fit items-center gap-2 rounded-full bg-[var(--accent)] px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-orange-500/20"><Plus className="h-4 w-4"/>Create Gift Card</motion.button></div>
    <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="rounded-[1.75rem] border border-[var(--border)] bg-[var(--bg-surface)] p-4 shadow-lg shadow-black/5"><label className="flex max-w-xl items-center gap-3 rounded-2xl border border-[var(--border)] bg-[var(--bg-muted)] px-4 py-3"><Search className="h-4 w-4 text-[var(--text-muted)]"/><span className="sr-only">Search gift cards</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search gift card code, value, or status" className="min-w-0 flex-1 bg-transparent text-sm text-[var(--text-primary)] outline-none"/></label><p className="mt-4 text-xs text-[var(--text-muted)]">Showing {visible.length} of {filtered.length} matching gift cards</p></motion.section>
    {loading ? <Skeleton/> : error ? <ErrorState message={error} onRetry={() => setReloadKey((value) => value + 1)}/> : visible.length ? <><DesktopTable cards={visible} busyId={busyId} onAction={setConfirmation}/><MobileCards cards={visible} busyId={busyId} onAction={setConfirmation}/></> : <Empty filtered={cards.length > 0} onReset={() => setSearch('')}/>} 
    {!loading && !error && filtered.length > PAGE_SIZE && <Pagination page={page} totalPages={totalPages} onPage={setPage}/>} 
    <AnimatePresence>{creating && <CreateModal onClose={() => setCreating(false)} onCreated={(card) => { setCards((current) => [card, ...current]); setCreating(false); }}/>}</AnimatePresence>
    <AnimatePresence>{confirmation && <ConfirmModal confirmation={confirmation} busy={busyId === documentId(confirmation.card._id)} onClose={() => !busyId && setConfirmation(null)} onConfirm={confirmAction}/>}</AnimatePresence>
  </div>;
}

function DesktopTable({ cards, busyId, onAction }) { return <div className="hidden overflow-hidden rounded-[2rem] border border-[var(--border)] bg-[var(--bg-surface)] shadow-lg shadow-black/5 md:block"><table className="w-full text-left"><thead className="border-b border-[var(--border)] bg-[var(--bg-muted)] text-[10px] font-bold uppercase tracking-[0.14em] text-[var(--text-muted)]"><tr>{['Gift Card Code','Value','Expiry Date','Status','Actions'].map((label) => <th key={label} className="px-6 py-4">{label}</th>)}</tr></thead><tbody>{cards.map((card, index) => <motion.tr key={documentId(card._id)} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.04 }} className="border-b border-[var(--border)] last:border-0 hover:bg-[var(--bg-muted)]/60"><td className="px-6 py-5"><Code value={card.code}/></td><td className="px-6 py-5 text-base font-bold text-[var(--text-primary)]">{money(card.value)}</td><td className="px-6 py-5 text-sm text-[var(--text-secondary)]">{date(card.expiryDate)}</td><td className="px-6 py-5"><Status status={card.status}/></td><td className="px-6 py-5"><Actions card={card} busy={busyId === documentId(card._id)} onAction={onAction}/></td></motion.tr>)}</tbody></table></div>; }
function MobileCards({ cards, busyId, onAction }) { return <div className="grid gap-4 sm:grid-cols-2 md:hidden">{cards.map((card, index) => <motion.article key={documentId(card._id)} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.04 }} className="relative overflow-hidden rounded-[1.75rem] border border-[var(--border)] bg-[var(--bg-surface)] p-5 shadow-lg shadow-black/5"><div className="absolute -right-7 -top-7 h-24 w-24 rounded-full bg-[var(--accent-soft)]"/><div className="relative flex items-start justify-between gap-3"><Code value={card.code}/><Status status={card.status}/></div><div className="relative mt-7 grid grid-cols-2 gap-3"><Field label="Value" value={money(card.value)}/><Field label="Expiry Date" value={date(card.expiryDate)}/></div><div className="relative mt-5 border-t border-[var(--border)] pt-4"><Actions card={card} busy={busyId === documentId(card._id)} onAction={onAction}/></div></motion.article>)}</div>; }
function Code({ value }) { return <span className="inline-flex rounded-xl bg-[var(--accent-soft)] px-3 py-2 font-mono text-xs font-bold tracking-wider text-[var(--accent)]">{value}</span>; }
function Status({ status }) { const active = status === 'active'; return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold capitalize ${active ? 'bg-emerald-500/10 text-emerald-500' : 'bg-slate-500/10 text-slate-500'}`}>{status}</span>; }
function Field({ label, value }) { return <div className="rounded-xl bg-[var(--bg-muted)] p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-[var(--text-muted)]">{label}</p><p className="mt-2 text-xs font-semibold text-[var(--text-primary)]">{value}</p></div>; }
function Actions({ card, busy, onAction }) { return <div className="flex flex-wrap gap-2">{card.status === 'active' && <Button label="Deactivate" icon={Ban} disabled={busy} onClick={() => onAction({ type: 'deactivate', card })}/>}<Button label="Delete" icon={Trash2} danger disabled={busy} onClick={() => onAction({ type: 'delete', card })}/>{busy && <Loader2 className="h-4 w-4 animate-spin self-center text-[var(--accent)]"/>}</div>; }
function Button({ label, icon: Icon, danger, ...props }) { return <button type="button" {...props} className={`inline-flex h-9 items-center gap-1.5 rounded-full border px-3 text-[10px] font-semibold transition disabled:opacity-40 ${danger ? 'border-red-500/20 text-red-500 hover:bg-red-500/10' : 'border-[var(--border)] text-[var(--text-secondary)] hover:text-[var(--accent)]'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>; }
function Modal({ title, onClose, children, small }) { return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" onMouseDown={onClose}><motion.div initial={{ opacity: 0, y: 18, scale: 0.97 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 12, scale: 0.97 }} onMouseDown={(event) => event.stopPropagation()} className={`w-full rounded-[2rem] border border-[var(--border)] bg-[var(--bg-surface)] p-6 shadow-[var(--shadow-elevated)] ${small ? 'max-w-lg' : 'max-w-xl'}`}><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-semibold text-[var(--text-primary)]">{title}</h2><button type="button" onClick={onClose} aria-label="Close modal" className="flex h-9 w-9 items-center justify-center rounded-full border border-[var(--border)] text-[var(--text-muted)]"><X className="h-4 w-4"/></button></div>{children}</motion.div></motion.div>; }
function CreateModal({ onClose, onCreated }) { const [form, setForm] = useState({ code: '', value: '', expiryDate: '', status: 'active' }); const [saving, setSaving] = useState(false); const set = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value })); async function submit(event) { event.preventDefault(); if (saving) return; setSaving(true); try { const response = await createGiftCard(form); onCreated(response.data.data); toast.success(response.data.message); } catch (error) { toast.error(error.response?.data?.message || 'Unable to create gift card.'); } finally { setSaving(false); } } return <Modal title="Create Gift Card" onClose={() => !saving && onClose()}><form onSubmit={submit} className="space-y-5"><Input label="Gift Card Code" value={form.code} onChange={set('code')} placeholder="GIFT-2026" required/><Input label="Value" type="number" min="0.01" step="0.01" value={form.value} onChange={set('value')} required/><Input label="Expiry Date" type="date" value={form.expiryDate} onChange={set('expiryDate')} required/><label className="block text-sm font-semibold text-[var(--text-secondary)]">Status<select value={form.status} onChange={set('status')} className="mt-2 w-full rounded-2xl border border-[var(--border)] bg-[var(--bg-muted)] px-4 py-3 text-[var(--text-primary)] outline-none"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><div className="flex justify-end gap-3 border-t border-[var(--border)] pt-5"><button type="button" onClick={onClose} disabled={saving} className="rounded-full border border-[var(--border)] px-5 py-2.5 text-sm font-semibold text-[var(--text-secondary)]">Cancel</button><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-full bg-[var(--accent)] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving && <Loader2 className="h-4 w-4 animate-spin"/>}{saving ? 'Creating...' : 'Create Gift Card'}</button></div></form></Modal>; }
function Input({ label, ...props }) { return <label className="block text-sm font-semibold text-[var(--text-secondary)]">{label}<input {...props} className="mt-2 w-full rounded-2xl border border-[var(--border)] bg-[var(--bg-muted)] px-4 py-3 text-[var(--text-primary)] outline-none focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--accent-soft)]"/></label>; }
function ConfirmModal({ confirmation, busy, onClose, onConfirm }) { const deleting = confirmation.type === 'delete'; return <Modal title={deleting ? 'Delete Gift Card?' : 'Deactivate Gift Card?'} onClose={onClose} small><div className={`flex h-14 w-14 items-center justify-center rounded-2xl ${deleting ? 'bg-red-500/10 text-red-500' : 'bg-amber-500/10 text-amber-500'}`}>{deleting ? <Trash2 className="h-7 w-7"/> : <Ban className="h-7 w-7"/>}</div><p className="mt-5 text-sm leading-7 text-[var(--text-secondary)]">{deleting ? 'This permanently removes the gift card.' : 'This gift card will no longer be usable.'}</p><Code value={confirmation.card.code}/><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={onClose} disabled={busy} className="rounded-full border border-[var(--border)] px-5 py-2.5 text-sm font-semibold text-[var(--text-secondary)]">Cancel</button><button type="button" onClick={onConfirm} disabled={busy} className={`inline-flex items-center gap-2 rounded-full px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50 ${deleting ? 'bg-red-500' : 'bg-amber-500'}`}>{busy && <Loader2 className="h-4 w-4 animate-spin"/>}{busy ? 'Updating...' : deleting ? 'Delete Gift Card' : 'Deactivate'}</button></div></Modal>; }
function Pagination({ page, totalPages, onPage }) { return <div className="flex items-center justify-between rounded-2xl border border-[var(--border)] bg-[var(--bg-surface)] px-4 py-3"><p className="text-xs text-[var(--text-muted)]">Page {page} of {totalPages}</p><div className="flex gap-2"><button type="button" aria-label="Previous page" disabled={page === 1} onClick={() => onPage(page - 1)} className="flex h-9 w-9 items-center justify-center rounded-full border border-[var(--border)] disabled:opacity-35"><ChevronLeft className="h-4 w-4"/></button><button type="button" aria-label="Next page" disabled={page === totalPages} onClick={() => onPage(page + 1)} className="flex h-9 w-9 items-center justify-center rounded-full border border-[var(--border)] disabled:opacity-35"><ChevronRight className="h-4 w-4"/></button></div></div>; }
function Skeleton() { return <div className="space-y-3" role="status" aria-label="Loading gift cards">{Array.from({ length: 6 }, (_, index) => <div key={index} className="h-20 animate-pulse rounded-2xl bg-[var(--bg-muted)]"/>)}</div>; }
function ErrorState({ message, onRetry }) { return <div className="rounded-[2rem] border border-red-500/20 bg-red-500/5 px-6 py-16 text-center"><p className="text-sm font-semibold text-red-500">{message}</p><button type="button" onClick={onRetry} className="mt-5 inline-flex items-center gap-2 rounded-full border border-red-500/20 px-5 py-2.5 text-sm font-semibold text-red-500"><RefreshCw className="h-4 w-4"/>Try Again</button></div>; }
function Empty({ filtered, onReset }) { return <div className="rounded-[2rem] border border-dashed border-[var(--border)] bg-[var(--bg-surface)] px-6 py-20 text-center"><Gift className="mx-auto h-10 w-10 text-[var(--accent)]"/><h2 className="mt-5 text-xl font-semibold text-[var(--text-primary)]">{filtered ? 'No matching gift cards' : 'No gift cards yet'}</h2><p className="mt-2 text-sm text-[var(--text-muted)]">{filtered ? 'Try another search.' : 'Create the first HomeBite gift card.'}</p>{filtered && <button type="button" onClick={onReset} className="mt-5 rounded-full border border-[var(--border)] px-5 py-2.5 text-sm font-semibold text-[var(--text-primary)]">Clear Search</button>}</div>; }
