import { flexRender, getCoreRowModel, getFilteredRowModel, getPaginationRowModel, getSortedRowModel, useReactTable } from '@tanstack/react-table';
import { motion } from 'framer-motion';
import { CalendarRange, ChevronDown, ChevronLeft, ChevronRight, ChevronsUpDown, Download, FileBarChart, FileText, Loader2, Printer, RefreshCw, Search, SlidersHorizontal, Users } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import DatePicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';
import { Controller, useForm } from 'react-hook-form';
import toast from 'react-hot-toast';
import Select from 'react-select';
import DashboardHeader from '../../components/dashboard/DashboardHeader';
import { generateAdminReport, getReportBootstrap } from '../../services/adminApi';

const label = (value) => String(value || '').replaceAll('-', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const reportTypes = [['orders','Orders Report'],['revenue','Revenue Report'],['customers','Customer Report'],['chefs','Chef Report'],['foods','Foods Report'],['reviews','Reviews Report'],['payments','Payments Report']].map(([value, label]) => ({ value, label }));
const statuses = ['pending','accepted','preparing','ready','out-for-delivery','delivered','cancelled','active','inactive','approved','rejected'].map((value) => ({ value, label: label(value) }));
const paymentStatuses = ['paid','pending','failed','refunded'].map((value) => ({ value, label: label(value) }));
const roleOptions = ['customer','chef','admin'].map((value) => ({ value, label: label(value) }));
const defaults = { reportType: 'orders', startDate: null, endDate: null, status: '', role: '', category: '', chef: '', customer: '', paymentStatus: '', search: '' };
const money = (value) => new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT', maximumFractionDigits: 2 }).format(Number(value || 0));
const date = (value) => value ? new Intl.DateTimeFormat('en-BD', { dateStyle: 'medium' }).format(new Date(value)) : 'Not available';
const documentId = (value) => value?.$oid || value || '';
const selectStyles = { control: (base, state) => ({ ...base, minHeight: 50, borderRadius: 16, borderColor: state.isFocused ? 'var(--accent)' : 'var(--border)', background: 'var(--bg-muted)', boxShadow: state.isFocused ? '0 0 0 2px var(--accent-soft)' : 'none' }), menu: (base) => ({ ...base, zIndex: 60, background: 'var(--bg-surface)', border: '1px solid var(--border)' }), option: (base, state) => ({ ...base, background: state.isSelected ? 'var(--accent)' : state.isFocused ? 'var(--bg-muted)' : 'var(--bg-surface)', color: state.isSelected ? '#fff' : 'var(--text-primary)' }), singleValue: (base) => ({ ...base, color: 'var(--text-primary)' }), input: (base) => ({ ...base, color: 'var(--text-primary)' }), placeholder: (base) => ({ ...base, color: 'var(--text-muted)' }) };

const columnSets = {
  orders: [['id','Order ID'],['customer','Customer'],['chef','Chef'],['total','Total','money'],['status','Status','badge'],['payment','Payment','badge'],['createdDate','Created Date','date']],
  revenue: [['date','Date','date'],['revenue','Revenue','money'],['orders','Orders'],['averageOrderValue','Average Order Value','money']],
  customers: [['name','Name'],['email','Email'],['orders','Orders'],['spent','Spent','money'],['joinedDate','Joined Date','date']],
  chefs: [['kitchenName','Kitchen Name'],['orders','Orders'],['revenue','Revenue','money'],['rating','Rating'],['verificationStatus','Verification Status','badge']],
  foods: [['foodName','Food Name'],['chef','Chef'],['category','Category'],['price','Price','money'],['orders','Orders'],['rating','Rating'],['availability','Availability','badge']],
  payments: [['transactionId','Transaction ID'],['customer','Customer'],['amount','Amount','money'],['method','Method'],['status','Status','badge'],['date','Date','date']],
  reviews: [['food','Food'],['chef','Chef'],['customer','Customer'],['rating','Rating'],['reviewDate','Review Date','date']]
};

export default function AdminReports() {
  const [bootstrap, setBootstrap] = useState({ chefs: [], customers: [], categories: [], recentReports: [] });
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState('');
  const [rows, setRows] = useState([]);
  const [currentType, setCurrentType] = useState('orders');
  const [generated, setGenerated] = useState(false);
  const { control, register, handleSubmit, reset, watch, formState: { isSubmitting } } = useForm({ defaultValues: defaults });

  useEffect(() => { let active = true; setLoading(true); getReportBootstrap().then((response) => { if (active) setBootstrap(response.data.data || {}); }).catch((error) => { if (active) setLoadError(error.response?.data?.message || 'Unable to load report tools.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);

  async function generate(values) {
    try {
      const filters = { ...values, startDate: values.startDate?.toISOString(), endDate: values.endDate?.toISOString() };
      delete filters.reportType;
      const response = await generateAdminReport({ reportType: values.reportType, filters });
      setRows(response.data.data.rows || []); setCurrentType(values.reportType); setGenerated(true);
      setBootstrap((current) => ({ ...current, recentReports: [response.data.data.report, ...(current.recentReports || [])].slice(0, 8) }));
      toast.success(`Generated ${response.data.data.rows?.length || 0} report rows.`);
    } catch (error) { toast.error(error.response?.data?.message || 'Unable to generate report.'); }
  }
  const placeholder = (name) => toast(`${name} export is coming soon.`);

  if (loading) return <ReportsSkeleton/>;
  return <div className="mx-auto max-w-[1600px] space-y-8">
    <DashboardHeader title="Reports" description="Generate historical operational and financial reports across HomeBite."/>
    {loadError && <div role="alert" className="rounded-2xl border border-red-500/20 bg-red-500/5 p-5 text-sm text-red-500">{loadError}</div>}
    <motion.form onSubmit={handleSubmit(generate)} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="rounded-[2rem] border border-[var(--border)] bg-[var(--bg-surface)] p-5 shadow-lg shadow-black/5 sm:p-6" aria-label="Report filters">
      <div className="mb-6 flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><SlidersHorizontal className="h-5 w-5"/></span><div><h2 className="text-lg font-semibold text-[var(--text-primary)]">Filter Panel</h2><p className="mt-1 text-xs text-[var(--text-muted)]">Select a report type and narrow the historical dataset.</p></div></div>
      <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><SelectField label="Report Type" name="reportType" control={control} options={reportTypes} required/><DateField label="Start Date" name="startDate" control={control} maxDate={watch('endDate') || new Date()}/><DateField label="End Date" name="endDate" control={control} minDate={watch('startDate')} maxDate={new Date()}/><SelectField label="Status" name="status" control={control} options={statuses} clearable/><SelectField label="Role" name="role" control={control} options={roleOptions} clearable/><SelectField label="Category" name="category" control={control} options={(bootstrap.categories || []).map((item) => ({ value: item, label: item }))} clearable/><SelectField label="Chef" name="chef" control={control} options={(bootstrap.chefs || []).map((item) => ({ value: item.email, label: item.name }))} clearable/><SelectField label="Customer" name="customer" control={control} options={(bootstrap.customers || []).map((item) => ({ value: item.email, label: item.name }))} clearable/><SelectField label="Payment Status" name="paymentStatus" control={control} options={paymentStatuses} clearable/><label className="block sm:col-span-2 xl:col-span-3"><span className="text-sm font-semibold text-[var(--text-secondary)]">Search</span><span className="mt-2 flex h-[50px] items-center gap-3 rounded-2xl border border-[var(--border)] bg-[var(--bg-muted)] px-4"><Search className="h-4 w-4 text-[var(--text-muted)]"/><input {...register('search')} placeholder="Search IDs, names, email, food, or transaction" className="min-w-0 flex-1 bg-transparent text-sm text-[var(--text-primary)] outline-none"/></span></label></div>
      <div className="mt-6 flex flex-col-reverse gap-3 border-t border-[var(--border)] pt-5 sm:flex-row sm:justify-end"><button type="button" onClick={() => { reset(defaults); setRows([]); setGenerated(false); }} className="rounded-full border border-[var(--border)] px-5 py-3 text-sm font-semibold text-[var(--text-secondary)]">Reset</button><motion.button whileHover={!isSubmitting ? { y: -2 } : {}} whileTap={!isSubmitting ? { scale: 0.98 } : {}} type="submit" disabled={isSubmitting || Boolean(loadError)} className="inline-flex min-w-44 items-center justify-center gap-2 rounded-full bg-gradient-to-r from-orange-500 to-rose-500 px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-orange-500/20 disabled:opacity-50">{isSubmitting ? <Loader2 className="h-4 w-4 animate-spin"/> : <FileBarChart className="h-4 w-4"/>}{isSubmitting ? 'Generating...' : 'Generate Report'}</motion.button></div>
    </motion.form>
    <motion.section initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="rounded-[2rem] border border-[var(--border)] bg-[var(--bg-surface)] shadow-lg shadow-black/5"><div className="flex flex-col gap-4 border-b border-[var(--border)] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><h2 className="text-lg font-semibold text-[var(--text-primary)]">{label(currentType)} Report</h2><p className="mt-1 text-xs text-[var(--text-muted)]">{generated ? `${rows.length} generated rows` : 'Configure filters and generate a report.'}</p></div><div className="flex flex-wrap gap-2"><ExportButton icon={Download} label="Export CSV" onClick={() => placeholder('CSV')}/><ExportButton icon={FileText} label="Export PDF" onClick={() => placeholder('PDF')}/><ExportButton icon={Printer} label="Print Report" onClick={() => placeholder('Print')}/></div></div>{generated ? <ReportTable type={currentType} data={rows}/> : <EmptyReport/>}</motion.section>
    <RecentReports reports={bootstrap.recentReports || []}/>
  </div>;
}

function SelectField({ label: text, name, control, options, clearable, required }) { return <label className="block"><span className="text-sm font-semibold text-[var(--text-secondary)]">{text}</span><Controller name={name} control={control} rules={required ? { required: true } : undefined} render={({ field }) => <Select inputId={`report-${name}`} aria-label={text} options={options} isClearable={clearable} styles={selectStyles} value={options.find((option) => option.value === field.value) || null} onChange={(option) => field.onChange(option?.value || '')} onBlur={field.onBlur}/>} /></label>; }
function DateField({ label: text, name, control, ...props }) { return <label className="block"><span className="text-sm font-semibold text-[var(--text-secondary)]">{text}</span><Controller name={name} control={control} render={({ field }) => <span className="relative mt-2 block"><CalendarRange className="pointer-events-none absolute left-4 top-4 z-10 h-4 w-4 text-[var(--text-muted)]"/><DatePicker selected={field.value} onChange={field.onChange} dateFormat="dd MMM yyyy" placeholderText="Select date" className="h-[50px] w-full rounded-2xl border border-[var(--border)] bg-[var(--bg-muted)] pl-11 pr-4 text-sm text-[var(--text-primary)] outline-none focus:border-[var(--accent)]" {...props}/></span>}/></label>; }

function ReportTable({ type, data }) {
  const [sorting, setSorting] = useState([]); const [columnFilters, setColumnFilters] = useState([]);
  const columns = useMemo(() => (columnSets[type] || []).map(([key, header, format]) => ({ accessorKey: key, header, cell: ({ getValue }) => <Cell value={getValue()} format={format} keyName={key}/> })), [type]);
  const table = useReactTable({ data, columns, state: { sorting, columnFilters }, onSortingChange: setSorting, onColumnFiltersChange: setColumnFilters, getCoreRowModel: getCoreRowModel(), getSortedRowModel: getSortedRowModel(), getFilteredRowModel: getFilteredRowModel(), getPaginationRowModel: getPaginationRowModel(), initialState: { pagination: { pageSize: 10 } } });
  if (!data.length) return <div className="px-6 py-20 text-center"><FileBarChart className="mx-auto h-10 w-10 text-[var(--text-muted)]"/><h3 className="mt-4 font-semibold text-[var(--text-primary)]">No matching report data</h3><p className="mt-2 text-sm text-[var(--text-muted)]">Adjust the filters and generate the report again.</p></div>;
  return <><div className="max-h-[650px] overflow-auto"><table className="w-full min-w-[900px] text-left"><thead className="sticky top-0 z-10 bg-[var(--bg-muted)]"><tr>{table.getHeaderGroups()[0].headers.map((header) => <th key={header.id} className="border-b border-[var(--border)] px-5 py-4"><button type="button" onClick={header.column.getToggleSortingHandler()} className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.13em] text-[var(--text-muted)]" aria-label={`Sort by ${header.column.columnDef.header}`}>{flexRender(header.column.columnDef.header, header.getContext())}<ChevronsUpDown className="h-3.5 w-3.5"/></button><input value={header.column.getFilterValue() || ''} onChange={(event) => header.column.setFilterValue(event.target.value)} aria-label={`Filter ${header.column.columnDef.header}`} placeholder="Filter..." className="mt-2 block w-full max-w-40 rounded-lg border border-[var(--border)] bg-[var(--bg-surface)] px-2 py-1.5 text-[10px] font-normal normal-case tracking-normal text-[var(--text-primary)] outline-none"/></th>)}</tr></thead><tbody>{table.getRowModel().rows.map((row, index) => <motion.tr key={row.id} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.025 }} className="border-b border-[var(--border)] last:border-0 hover:bg-[var(--bg-muted)]/60">{row.getVisibleCells().map((cell) => <td key={cell.id} className="max-w-[260px] px-5 py-4 text-xs text-[var(--text-secondary)]">{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</motion.tr>)}</tbody></table></div><div className="flex flex-col gap-4 border-t border-[var(--border)] p-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-[var(--text-muted)]">Page {table.getState().pagination.pageIndex + 1} of {table.getPageCount()} · {table.getFilteredRowModel().rows.length} rows</p><div className="flex gap-2"><PageButton label="Previous page" disabled={!table.getCanPreviousPage()} onClick={() => table.previousPage()}><ChevronLeft className="h-4 w-4"/></PageButton><PageButton label="Next page" disabled={!table.getCanNextPage()} onClick={() => table.nextPage()}><ChevronRight className="h-4 w-4"/></PageButton></div></div></>;
}
function Cell({ value, format, keyName }) { if (format === 'money') return <strong className="text-[var(--text-primary)]">{money(value)}</strong>; if (format === 'date') return date(value); if (format === 'badge') return <span className="inline-flex rounded-full bg-[var(--accent-soft)] px-2.5 py-1 text-[10px] font-bold capitalize text-[var(--accent)]">{label(value)}</span>; if (keyName === 'id' || keyName === 'transactionId') return <span className="font-mono text-[11px] text-[var(--text-primary)]">{String(value || '').slice(-12).toUpperCase()}</span>; return String(value ?? '—'); }
function ExportButton({ icon: Icon, label: text, onClick }) { return <motion.button whileTap={{ scale: 0.96 }} type="button" onClick={onClick} className="inline-flex items-center gap-2 rounded-full border border-[var(--border)] px-3 py-2 text-xs font-semibold text-[var(--text-secondary)] hover:text-[var(--accent)]"><Icon className="h-3.5 w-3.5"/>{text}</motion.button>; }
function PageButton({ label: text, children, ...props }) { return <button type="button" aria-label={text} {...props} className="flex h-9 w-9 items-center justify-center rounded-full border border-[var(--border)] text-[var(--text-secondary)] disabled:opacity-35">{children}</button>; }
function EmptyReport() { return <div className="px-6 py-24 text-center"><FileBarChart className="mx-auto h-12 w-12 text-[var(--accent)]"/><h3 className="mt-5 text-lg font-semibold text-[var(--text-primary)]">Generate your first report</h3><p className="mt-2 text-sm text-[var(--text-muted)]">Choose a report type and filters above to build the table.</p></div>; }
function RecentReports({ reports }) { return <motion.section initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="rounded-[2rem] border border-[var(--border)] bg-[var(--bg-surface)] p-5 shadow-lg shadow-black/5 sm:p-6"><div className="mb-5 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><RefreshCw className="h-4 w-4"/></span><div><h2 className="text-lg font-semibold text-[var(--text-primary)]">Recent Reports</h2><p className="mt-1 text-xs text-[var(--text-muted)]">Previously generated report runs.</p></div></div>{reports.length ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{reports.map((report, index) => <motion.article key={documentId(report._id) || index} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.035 }} className="rounded-2xl bg-[var(--bg-muted)] p-4"><div className="flex items-center justify-between gap-3"><FileText className="h-4 w-4 text-[var(--accent)]"/><span className="text-[10px] text-[var(--text-muted)]">{date(report.generatedAt)}</span></div><p className="mt-4 text-sm font-semibold text-[var(--text-primary)]">{label(report.reportType)} Report</p><p className="mt-2 text-xs text-[var(--text-muted)]">{report.rowCount || 0} generated rows</p></motion.article>)}</div> : <div className="rounded-2xl border border-dashed border-[var(--border)] px-5 py-12 text-center text-sm text-[var(--text-muted)]">Generated reports will appear here.</div>}</motion.section>; }
function ReportsSkeleton() { return <div className="mx-auto max-w-[1600px] space-y-8" role="status" aria-label="Loading reports"><div className="space-y-3"><Shimmer className="h-4 w-32"/><Shimmer className="h-10 w-72"/></div><Shimmer className="h-[430px] rounded-[2rem]"/><Shimmer className="h-[500px] rounded-[2rem]"/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <Shimmer key={index} className="h-36 rounded-3xl"/>)}</div></div>; }
function Shimmer({ className }) { return <div className={`relative overflow-hidden bg-[var(--bg-muted)] ${className}`}><motion.span animate={{ x: ['-120%', '220%'] }} transition={{ duration: 1.5, repeat: Infinity, ease: 'linear' }} className="absolute inset-y-0 w-1/2 bg-gradient-to-r from-transparent via-white/15 to-transparent"/></div>; }
