import { AnimatePresence, motion } from 'framer-motion';
import { CheckCircle2, ChevronLeft, ChevronRight, Loader2, Pencil, Plus, RefreshCw, Search, TicketPercent, Trash2, X, XCircle } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import DashboardHeader from '../../components/dashboard/DashboardHeader';
import { createCoupon, deleteCoupon, getCoupons, updateCoupon, updateCouponStatus } from '../../services/adminApi';

const PAGE_SIZE = 8;
const emptyForm = { code: '', description: '', discountType: 'percentage', percentage: '', fixedAmount: '', minimumOrder: '', maximumDiscount: '', expiryDate: '', status: 'active' };
const documentId = (value) => value?.$oid || value || '';
const money = (value) => new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT', maximumFractionDigits: 2 }).format(Number(value || 0));
const date = (value) => value ? new Intl.DateTimeFormat('en-BD', { dateStyle: 'medium' }).format(new Date(value)) : 'Not available';

export default function AdminCoupons() {
  const [coupons, setCoupons] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [reloadKey, setReloadKey] = useState(0);
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [editing, setEditing] = useState(null);
  const [deleting, setDeleting] = useState(null);
  const [busyId, setBusyId] = useState('');

  useEffect(() => {
    let active = true; setLoading(true); setError('');
    getCoupons().then((response) => { if (active) setCoupons(response.data.data || []); })
      .catch((requestError) => { if (active) setError(requestError.response?.data?.message || 'Unable to load coupons.'); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [reloadKey]);

  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return coupons.filter((coupon) => !query || [coupon.code, coupon.description, coupon.discountType, coupon.status].join(' ').toLowerCase().includes(query)); }, [coupons, search]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  useEffect(() => setPage(1), [search]);
  useEffect(() => setPage((current) => Math.min(current, totalPages)), [totalPages]);

  function replaceCoupon(updated) { setCoupons((current) => current.map((coupon) => documentId(coupon._id) === documentId(updated._id) ? updated : coupon)); }
  async function setStatus(coupon) {
    const id = documentId(coupon._id); if (!id || busyId) return;
    const status = coupon.status === 'active' ? 'inactive' : 'active'; setBusyId(id);
    try { const response = await updateCouponStatus(id, status); replaceCoupon(response.data.data); toast.success(response.data.message); }
    catch (requestError) { toast.error(requestError.response?.data?.message || 'Unable to update coupon status.'); }
    finally { setBusyId(''); }
  }
  async function removeCoupon() {
    const id = documentId(deleting?._id); if (!id || busyId) return; setBusyId(id);
    try { await deleteCoupon(id); setCoupons((current) => current.filter((coupon) => documentId(coupon._id) !== id)); setDeleting(null); toast.success('Coupon deleted successfully.'); }
    catch (requestError) { toast.error(requestError.response?.data?.message || 'Unable to delete coupon.'); }
    finally { setBusyId(''); }
  }

  return <div className="mx-auto max-w-[1500px] space-y-8">
    <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><DashboardHeader title="Coupons" description="Create and manage promotional discounts across HomeBite."/><motion.button whileHover={{ y: -2 }} whileTap={{ scale: 0.97 }} type="button" onClick={() => setEditing({ mode: 'create' })} className="inline-flex w-fit items-center gap-2 rounded-full bg-[var(--accent)] px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-orange-500/20"><Plus className="h-4 w-4"/>Create Coupon</motion.button></div>
    <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="rounded-[1.75rem] border border-[var(--border)] bg-[var(--bg-surface)] p-4 shadow-lg shadow-black/5"><label className="flex max-w-xl items-center gap-3 rounded-2xl border border-[var(--border)] bg-[var(--bg-muted)] px-4 py-3"><Search className="h-4 w-4 text-[var(--text-muted)]"/><span className="sr-only">Search coupons</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search code, description, type, or status" className="min-w-0 flex-1 bg-transparent text-sm text-[var(--text-primary)] outline-none"/></label><p className="mt-4 text-xs text-[var(--text-muted)]">Showing {visible.length} of {filtered.length} matching coupons</p></motion.section>
    {loading ? <Skeleton/> : error ? <ErrorState message={error} onRetry={() => setReloadKey((value) => value + 1)}/> : visible.length ? <><DesktopTable coupons={visible} busyId={busyId} onEdit={(coupon) => setEditing({ mode: 'edit', coupon })} onStatus={setStatus} onDelete={setDeleting}/><MobileCards coupons={visible} busyId={busyId} onEdit={(coupon) => setEditing({ mode: 'edit', coupon })} onStatus={setStatus} onDelete={setDeleting}/></> : <Empty filtered={coupons.length > 0} onReset={() => setSearch('')}/>} 
    {!loading && !error && filtered.length > PAGE_SIZE && <Pagination page={page} totalPages={totalPages} onPage={setPage}/>} 
    <AnimatePresence>{editing && <CouponModal editing={editing} onClose={() => setEditing(null)} onSaved={(coupon) => { if (editing.mode === 'create') setCoupons((current) => [coupon, ...current]); else replaceCoupon(coupon); setEditing(null); }}/>}</AnimatePresence>
    <AnimatePresence>{deleting && <DeleteModal coupon={deleting} busy={busyId === documentId(deleting._id)} onClose={() => !busyId && setDeleting(null)} onConfirm={removeCoupon}/>}</AnimatePresence>
  </div>;
}

function DesktopTable({ coupons, busyId, onEdit, onStatus, onDelete }) { return <div className="hidden overflow-hidden rounded-[2rem] border border-[var(--border)] bg-[var(--bg-surface)] shadow-lg shadow-black/5 lg:block"><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-left"><thead className="border-b border-[var(--border)] bg-[var(--bg-muted)] text-[10px] font-bold uppercase tracking-[0.14em] text-[var(--text-muted)]"><tr>{['Coupon Code','Description','Discount','Minimum Order','Maximum Discount','Expiry Date','Status','Actions'].map((label) => <th key={label} className="px-5 py-4">{label}</th>)}</tr></thead><tbody>{coupons.map((coupon, index) => <motion.tr key={documentId(coupon._id)} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.035 }} className="border-b border-[var(--border)] last:border-0 hover:bg-[var(--bg-muted)]/60"><td className="px-5 py-5"><Code value={coupon.code}/></td><td className="px-5 py-5"><p className="max-w-[240px] truncate text-xs text-[var(--text-secondary)]" title={coupon.description}>{coupon.description}</p></td><td className="px-5 py-5 text-sm font-semibold text-[var(--text-primary)]">{discount(coupon)}</td><td className="px-5 py-5 text-xs text-[var(--text-secondary)]">{money(coupon.minimumOrder)}</td><td className="px-5 py-5 text-xs text-[var(--text-secondary)]">{coupon.maximumDiscount ? money(coupon.maximumDiscount) : 'No limit'}</td><td className="px-5 py-5 text-xs text-[var(--text-secondary)]">{date(coupon.expiryDate)}</td><td className="px-5 py-5"><Status status={coupon.status}/></td><td className="px-5 py-5"><Actions coupon={coupon} busy={busyId === documentId(coupon._id)} onEdit={onEdit} onStatus={onStatus} onDelete={onDelete}/></td></motion.tr>)}</tbody></table></div></div>; }
function MobileCards({ coupons, busyId, onEdit, onStatus, onDelete }) { return <div className="grid gap-4 sm:grid-cols-2 lg:hidden">{coupons.map((coupon, index) => <motion.article key={documentId(coupon._id)} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.04 }} className="rounded-[1.75rem] border border-[var(--border)] bg-[var(--bg-surface)] p-5 shadow-lg shadow-black/5"><div className="flex items-start justify-between gap-3"><Code value={coupon.code}/><Status status={coupon.status}/></div><p className="mt-4 text-sm leading-6 text-[var(--text-secondary)]">{coupon.description}</p><div className="mt-5 grid grid-cols-2 gap-3"><Field label="Discount" value={discount(coupon)}/><Field label="Minimum Order" value={money(coupon.minimumOrder)}/><Field label="Maximum Discount" value={coupon.maximumDiscount ? money(coupon.maximumDiscount) : 'No limit'}/><Field label="Expiry Date" value={date(coupon.expiryDate)}/></div><div className="mt-5 border-t border-[var(--border)] pt-4"><Actions coupon={coupon} busy={busyId === documentId(coupon._id)} onEdit={onEdit} onStatus={onStatus} onDelete={onDelete}/></div></motion.article>)}</div>; }
const discount = (coupon) => coupon.discountType === 'percentage' ? `${coupon.percentage}%` : money(coupon.fixedAmount);
function Code({ value }) { return <span className="inline-flex rounded-xl bg-[var(--accent-soft)] px-3 py-2 font-mono text-xs font-bold tracking-wider text-[var(--accent)]">{value}</span>; }
function Status({ status }) { const active = status === 'active'; return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold capitalize ${active ? 'bg-emerald-500/10 text-emerald-500' : 'bg-slate-500/10 text-slate-500'}`}>{status}</span>; }
function Field({ label, value }) { return <div className="rounded-xl bg-[var(--bg-muted)] p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-[var(--text-muted)]">{label}</p><p className="mt-2 text-xs font-semibold text-[var(--text-primary)]">{value}</p></div>; }
function Actions({ coupon, busy, onEdit, onStatus, onDelete }) { const active = coupon.status === 'active'; return <div className="flex min-w-[245px] flex-wrap gap-2"><Button label="Edit" icon={Pencil} disabled={busy} onClick={() => onEdit(coupon)}/><Button label={active ? 'Deactivate' : 'Activate'} icon={active ? XCircle : CheckCircle2} disabled={busy} success={!active} onClick={() => onStatus(coupon)}/><Button label="Delete" icon={Trash2} disabled={busy} danger onClick={() => onDelete(coupon)}/>{busy && <Loader2 className="h-4 w-4 animate-spin self-center text-[var(--accent)]"/>}</div>; }
function Button({ label, icon: Icon, disabled, onClick, danger, success }) { return <button type="button" disabled={disabled} onClick={onClick} className={`inline-flex h-9 items-center gap-1.5 rounded-full border px-3 text-[10px] font-semibold transition disabled:opacity-40 ${danger ? 'border-red-500/20 text-red-500 hover:bg-red-500/10' : success ? 'border-emerald-500/20 text-emerald-500 hover:bg-emerald-500/10' : 'border-[var(--border)] text-[var(--text-secondary)] hover:text-[var(--accent)]'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>; }

function Modal({ title, onClose, children, small = false }) { return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" onMouseDown={onClose}><motion.div initial={{ opacity: 0, y: 18, scale: 0.97 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 12, scale: 0.97 }} onMouseDown={(event) => event.stopPropagation()} className={`max-h-[92vh] w-full overflow-y-auto rounded-[2rem] border border-[var(--border)] bg-[var(--bg-surface)] p-6 shadow-[var(--shadow-elevated)] ${small ? 'max-w-lg' : 'max-w-3xl'}`}><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-semibold text-[var(--text-primary)]">{title}</h2><button type="button" onClick={onClose} aria-label="Close modal" className="flex h-9 w-9 items-center justify-center rounded-full border border-[var(--border)] text-[var(--text-muted)]"><X className="h-4 w-4"/></button></div>{children}</motion.div></motion.div>; }
function CouponModal({ editing, onClose, onSaved }) {
  const coupon = editing.coupon;
  const [form, setForm] = useState(coupon ? { ...emptyForm, ...coupon, expiryDate: coupon.expiryDate ? new Date(coupon.expiryDate).toISOString().slice(0, 10) : '' } : emptyForm);
  const [saving, setSaving] = useState(false);
  const set = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  async function submit(event) { event.preventDefault(); if (saving) return; setSaving(true); try { const response = editing.mode === 'create' ? await createCoupon(form) : await updateCoupon(documentId(coupon._id), form); onSaved(response.data.data); toast.success(response.data.message); } catch (error) { toast.error(error.response?.data?.message || 'Unable to save coupon.'); } finally { setSaving(false); } }
  return <Modal title={editing.mode === 'create' ? 'Create Coupon' : 'Edit Coupon'} onClose={() => !saving && onClose()}><form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><Input label="Coupon Code" value={form.code} onChange={set('code')} required placeholder="WELCOME20"/><Input label="Description" value={form.description} onChange={set('description')} required placeholder="Welcome discount"/><Select label="Discount Type" value={form.discountType} onChange={set('discountType')} options={[['percentage','Percentage'],['fixed','Fixed Amount']]}/>{form.discountType === 'percentage' ? <Input label="Percentage" type="number" min="1" max="100" step="0.01" value={form.percentage} onChange={set('percentage')} required/> : <Input label="Fixed Amount" type="number" min="0.01" step="0.01" value={form.fixedAmount} onChange={set('fixedAmount')} required/>}<Input label="Minimum Order" type="number" min="0" step="0.01" value={form.minimumOrder} onChange={set('minimumOrder')} required/><Input label="Maximum Discount" type="number" min="0" step="0.01" value={form.maximumDiscount} onChange={set('maximumDiscount')} required/><Input label="Expiry Date" type="date" value={form.expiryDate} onChange={set('expiryDate')} required/><Select label="Status" value={form.status} onChange={set('status')} options={[['active','Active'],['inactive','Inactive']]}/><div className="flex justify-end gap-3 border-t border-[var(--border)] pt-5 sm:col-span-2"><button type="button" disabled={saving} onClick={onClose} className="rounded-full border border-[var(--border)] px-5 py-2.5 text-sm font-semibold text-[var(--text-secondary)]">Cancel</button><button type="submit" disabled={saving} className="inline-flex items-center gap-2 rounded-full bg-[var(--accent)] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving && <Loader2 className="h-4 w-4 animate-spin"/>}{saving ? 'Saving...' : 'Save Coupon'}</button></div></form></Modal>;
}
function Input({ label, ...props }) { return <label className="text-sm font-semibold text-[var(--text-secondary)]">{label}<input {...props} className="mt-2 w-full rounded-2xl border border-[var(--border)] bg-[var(--bg-muted)] px-4 py-3 text-[var(--text-primary)] outline-none focus:border-[var(--accent)] focus:ring-2 focus:ring-[var(--accent-soft)]"/></label>; }
function Select({ label, options, ...props }) { return <label className="text-sm font-semibold text-[var(--text-secondary)]">{label}<select {...props} className="mt-2 w-full rounded-2xl border border-[var(--border)] bg-[var(--bg-muted)] px-4 py-3 text-[var(--text-primary)] outline-none focus:border-[var(--accent)]">{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>; }
function DeleteModal({ coupon, busy, onClose, onConfirm }) { return <Modal title="Delete Coupon?" onClose={onClose} small><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-red-500/10 text-red-500"><Trash2 className="h-7 w-7"/></div><p className="mt-5 text-sm leading-7 text-[var(--text-secondary)]">This permanently removes coupon <strong className="text-[var(--text-primary)]">{coupon.code}</strong>. This action cannot be undone.</p><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={onClose} disabled={busy} className="rounded-full border border-[var(--border)] px-5 py-2.5 text-sm font-semibold text-[var(--text-secondary)]">Cancel</button><button type="button" onClick={onConfirm} disabled={busy} className="inline-flex items-center gap-2 rounded-full bg-red-500 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy && <Loader2 className="h-4 w-4 animate-spin"/>}{busy ? 'Deleting...' : 'Delete Coupon'}</button></div></Modal>; }
function Pagination({ page, totalPages, onPage }) { return <div className="flex items-center justify-between rounded-2xl border border-[var(--border)] bg-[var(--bg-surface)] px-4 py-3"><p className="text-xs text-[var(--text-muted)]">Page {page} of {totalPages}</p><div className="flex gap-2"><button aria-label="Previous page" disabled={page === 1} onClick={() => onPage(page - 1)} className="flex h-9 w-9 items-center justify-center rounded-full border border-[var(--border)] disabled:opacity-35"><ChevronLeft className="h-4 w-4"/></button><button aria-label="Next page" disabled={page === totalPages} onClick={() => onPage(page + 1)} className="flex h-9 w-9 items-center justify-center rounded-full border border-[var(--border)] disabled:opacity-35"><ChevronRight className="h-4 w-4"/></button></div></div>; }
function Skeleton() { return <div className="space-y-3" role="status" aria-label="Loading coupons">{Array.from({ length: 6 }, (_, index) => <div key={index} className="h-20 animate-pulse rounded-2xl bg-[var(--bg-muted)]"/>)}</div>; }
function ErrorState({ message, onRetry }) { return <div className="rounded-[2rem] border border-red-500/20 bg-red-500/5 px-6 py-16 text-center"><p className="text-sm font-semibold text-red-500">{message}</p><button onClick={onRetry} className="mt-5 inline-flex items-center gap-2 rounded-full border border-red-500/20 px-5 py-2.5 text-sm font-semibold text-red-500"><RefreshCw className="h-4 w-4"/>Try Again</button></div>; }
function Empty({ filtered, onReset }) { return <div className="rounded-[2rem] border border-dashed border-[var(--border)] bg-[var(--bg-surface)] px-6 py-20 text-center"><TicketPercent className="mx-auto h-10 w-10 text-[var(--accent)]"/><h2 className="mt-5 text-xl font-semibold text-[var(--text-primary)]">{filtered ? 'No matching coupons' : 'No coupons yet'}</h2><p className="mt-2 text-sm text-[var(--text-muted)]">{filtered ? 'Try another search.' : 'Create your first promotional coupon.'}</p>{filtered && <button onClick={onReset} className="mt-5 rounded-full border border-[var(--border)] px-5 py-2.5 text-sm font-semibold text-[var(--text-primary)]">Clear Search</button>}</div>; }
