import { motion } from 'framer-motion';
import { ArrowRight, Bell, ChefHat, CircleDollarSign, Clock3, Database, Gift, HeartHandshake, Mail, MessageCircle, ReceiptText, Server, Settings, ShieldCheck, ShoppingBag, Star, TicketPercent, UserRound, Users, Utensils, WalletCards, Wifi } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import DashboardHeader from '../../components/dashboard/DashboardHeader';
import useNotifications from '../../hooks/useNotifications';
import useSocket from '../../hooks/useSocket';
import { useAuth } from '../../providers/AuthProvider';
import { getAdminOverview } from '../../services/adminApi';

const documentId = (value) => value?.$oid || value || '';
const money = (value) => new Intl.NumberFormat('en-BD', { style: 'currency', currency: 'BDT', maximumFractionDigits: 0 }).format(Number(value || 0));
const dateTime = (value) => value ? new Intl.DateTimeFormat('en-BD', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value)) : 'Not available';
const statusLabel = (value) => String(value || 'pending').replaceAll('-', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const statusTone = { pending: 'bg-amber-500/10 text-amber-500', accepted: 'bg-blue-500/10 text-blue-500', preparing: 'bg-violet-500/10 text-violet-500', ready: 'bg-cyan-500/10 text-cyan-500', 'out-for-delivery': 'bg-orange-500/10 text-orange-500', delivered: 'bg-emerald-500/10 text-emerald-500', rejected: 'bg-red-500/10 text-red-500' };

export default function AdminOverview() {
  const { user, dbUser } = useAuth();
  const { notifications, unreadCount, loading: notificationsLoading } = useNotifications();
  const { connected } = useSocket();
  const email = (dbUser?.email || user?.email || '').trim().toLowerCase();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [now, setNow] = useState(new Date());

  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { let active = true; setLoading(true); setError(''); getAdminOverview(email).then((response) => { if (active) setData(response.data.data); }).catch((requestError) => { if (active) setError(requestError.response?.data?.message || 'Unable to load the admin overview.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [email]);
  const greeting = useMemo(() => { const hour = now.getHours(); return hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'; }, [now]);
  if (loading || notificationsLoading) return <OverviewSkeleton/>;
  const stats = data?.stats || {}; const recent = data?.recent || { orders: [], users: [], reviews: [] };
  const snapshot = [
    { label: "Today's Orders", value: stats.todayOrders || 0, description: 'Orders placed since midnight', icon: ShoppingBag, tone: 'text-blue-500 bg-blue-500/10' },
    { label: "Today's Revenue", value: stats.todayRevenue || 0, money: true, description: 'Paid revenue collected today', icon: CircleDollarSign, tone: 'text-emerald-500 bg-emerald-500/10' },
    { label: 'New Users Today', value: stats.newUsersToday || 0, description: 'New platform registrations', icon: UserRound, tone: 'text-violet-500 bg-violet-500/10' },
    { label: 'Pending Chef Applications', value: stats.pendingApplications || 0, description: 'Applications awaiting review', icon: ChefHat, tone: 'text-orange-500 bg-orange-500/10' },
    { label: 'Unread Notifications', value: unreadCount, description: 'Administrative updates unread', icon: Bell, tone: 'text-rose-500 bg-rose-500/10' },
    { label: 'Orders Waiting For Chef', value: stats.ordersWaitingForChef || 0, description: 'Pending chef acceptance', icon: Clock3, tone: 'text-amber-500 bg-amber-500/10' }
  ];
  return <div className="mx-auto max-w-[1600px] space-y-8">
    <DashboardHeader title="Admin Overview" description="Immediate priorities, recent activity, and platform health at a glance."/>
    {error && <div role="alert" className="rounded-2xl border border-red-500/20 bg-red-500/5 p-5 text-sm text-red-500">{error}</div>}
    <WelcomeBanner name={dbUser?.name || user?.displayName || 'Admin'} greeting={greeting} now={now}/>
    <SectionHeading title="Today's Snapshot" description="The platform activity that matters right now."/><motion.section initial="hidden" animate="show" variants={{ hidden: {}, show: { transition: { staggerChildren: 0.045 } } }} className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{snapshot.map((item) => <SnapshotCard key={item.label} item={item}/>)}</motion.section>
    <PendingActions stats={stats}/>
    <section className="grid gap-6 xl:grid-cols-[1.45fr_0.75fr]"><Panel title="Recent Orders" description="Latest five platform orders" icon={ReceiptText}>{recent.orders?.length ? <RecentOrders orders={recent.orders}/> : <Empty text="No recent orders."/>}</Panel><Panel title="Recent Registered Users" description="Latest five accounts" icon={Users}>{recent.users?.length ? <div className="space-y-3">{recent.users.map((account, index) => <RecentUser key={documentId(account._id)} account={account} index={index}/>)}</div> : <Empty text="No recent users."/>}</Panel></section>
    <section className="grid gap-6 xl:grid-cols-2"><Panel title="Recent Notifications" description="Latest administrator updates" icon={Bell} action={<Link to="/dashboard/admin/notifications" className="inline-flex items-center gap-1 text-xs font-semibold text-[var(--accent)]">View All <ArrowRight className="h-3.5 w-3.5"/></Link>}>{notifications.length ? <div className="space-y-3">{notifications.slice(0, 5).map((notification, index) => <RecentNotification key={documentId(notification._id)} notification={notification} index={index}/>)}</div> : <Empty text="No notifications."/>}</Panel><Panel title="Recent Reviews" description="Latest customer feedback" icon={Star}>{recent.reviews?.length ? <div className="space-y-3">{recent.reviews.map((review, index) => <RecentReview key={documentId(review._id)} review={review} index={index}/>)}</div> : <Empty text="No recent reviews."/>}</Panel></section>
    <QuickActions/>
    <PlatformHealth health={data?.health || {}} connected={connected} firebaseOnline={Boolean(user)}/>
    <FooterSummary/>
  </div>;
}

function WelcomeBanner({ name, greeting, now }) { return <motion.section initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="relative isolate overflow-hidden rounded-[2.25rem] bg-gradient-to-br from-slate-950 via-violet-950 to-orange-950 p-6 text-white shadow-[0_30px_80px_rgba(30,41,59,0.24)] sm:p-8"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-orange-500/20 blur-3xl"/><div className="absolute -bottom-24 left-1/3 h-60 w-60 rounded-full bg-violet-500/20 blur-3xl"/><div className="relative flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-white/60">{greeting}</p><h2 className="mt-3 text-3xl font-semibold text-white sm:text-4xl">Welcome {name}</h2><p className="mt-3 text-sm text-white/70">Here is what needs your attention across HomeBite today.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-5 py-4 backdrop-blur"><p className="text-sm font-semibold text-white">{new Intl.DateTimeFormat('en-BD', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }).format(now)}</p><p className="mt-2 text-2xl font-bold tabular-nums text-orange-300">{new Intl.DateTimeFormat('en-BD', { hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(now)}</p><span className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-400"/>Platform Online</span></div></div></motion.section>; }
function SectionHeading({ title, description }) { return <div><h2 className="text-xl font-semibold text-[var(--text-primary)]">{title}</h2><p className="mt-1 text-sm text-[var(--text-muted)]">{description}</p></div>; }
function SnapshotCard({ item }) { const Icon = item.icon; return <motion.article variants={{ hidden: { opacity: 0, y: 14 }, show: { opacity: 1, y: 0 } }} whileHover={{ y: -3 }} className="rounded-[1.5rem] border border-[var(--border)] bg-[var(--bg-surface)] p-5 shadow-lg shadow-black/5"><span className={`flex h-11 w-11 items-center justify-center rounded-2xl ${item.tone}`}><Icon className="h-5 w-5"/></span><motion.p key={item.value} initial={{ opacity: 0.5, y: 3 }} animate={{ opacity: 1, y: 0 }} className="mt-5 text-2xl font-bold text-[var(--text-primary)]">{item.money ? money(item.value) : Number(item.value).toLocaleString('en-BD')}</motion.p><p className="mt-2 text-xs font-semibold text-[var(--text-secondary)]">{item.label}</p><p className="mt-2 text-[10px] leading-4 text-[var(--text-muted)]">{item.description}</p></motion.article>; }
function PendingActions({ stats }) { const items = [{ label: 'Pending Chef Applications', count: stats.pendingApplications || 0, priority: 'High', to: '/dashboard/admin/chef-verification', icon: ChefHat },{ label: 'Orders Waiting For Approval', count: stats.ordersWaitingForChef || 0, priority: 'High', to: '/dashboard/admin/orders', icon: Clock3 },{ label: 'Unread Contact Messages', count: stats.unreadMessages || 0, priority: 'Medium', to: '/dashboard/admin/messages', icon: MessageCircle },{ label: 'Reported Reviews', count: 0, priority: 'Placeholder', to: '/dashboard/admin/reports', icon: HeartHandshake }]; return <section><SectionHeading title="Pending Actions" description="Items that may require administrator intervention."/><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map((item, index) => { const Icon = item.icon; return <motion.article key={item.label} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.04 }} className="rounded-[1.5rem] border border-[var(--border)] bg-[var(--bg-surface)] p-5"><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><Icon className="h-5 w-5"/></span><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${item.priority === 'High' ? 'bg-red-500/10 text-red-500' : 'bg-amber-500/10 text-amber-500'}`}>{item.priority}</span></div><p className="mt-5 text-3xl font-bold text-[var(--text-primary)]">{item.count}</p><p className="mt-2 text-sm font-semibold text-[var(--text-secondary)]">{item.label}</p><Link to={item.to} className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-[var(--accent)]">Go To <ArrowRight className="h-3.5 w-3.5"/></Link></motion.article>; })}</div></section>; }
function Panel({ title, description, icon: Icon, action, children }) { return <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="rounded-[2rem] border border-[var(--border)] bg-[var(--bg-surface)] p-5 shadow-lg shadow-black/5 sm:p-6"><div className="mb-5 flex items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><Icon className="h-4 w-4"/></span><div><h2 className="font-semibold text-[var(--text-primary)]">{title}</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">{description}</p></div></div>{action}</div>{children}</motion.section>; }
function RecentOrders({ orders }) { return <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="text-[10px] font-bold uppercase tracking-wider text-[var(--text-muted)]"><tr>{['Customer','Chef','Amount','Status','Time','View'].map((item) => <th key={item} className="border-b border-[var(--border)] px-3 py-3">{item}</th>)}</tr></thead><tbody>{orders.slice(0,5).map((order) => <tr key={documentId(order._id)} className="border-b border-[var(--border)] last:border-0"><td className="px-3 py-4 text-xs font-semibold text-[var(--text-primary)]">{order.customer?.name || order.customer?.email || 'Customer'}</td><td className="px-3 py-4 text-xs text-[var(--text-secondary)]">{(Array.isArray(order.chef) ? order.chef : [order.chef].filter(Boolean)).map((chef) => chef.name || chef.email).join(', ') || 'Chef'}</td><td className="px-3 py-4 text-xs font-bold text-[var(--text-primary)]">{money(order.total)}</td><td className="px-3 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${statusTone[order.status] || 'bg-slate-500/10 text-slate-500'}`}>{statusLabel(order.status)}</span></td><td className="px-3 py-4 text-[10px] text-[var(--text-muted)]">{dateTime(order.orderDate)}</td><td className="px-3 py-4"><Link to="/dashboard/admin/orders" className="text-xs font-semibold text-[var(--accent)]">View</Link></td></tr>)}</tbody></table></div>; }
function RecentUser({ account, index }) { return <motion.article initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * 0.04 }} className="flex items-center gap-3 rounded-2xl bg-[var(--bg-muted)] p-3">{account.photo ? <img src={account.photo} alt="" className="h-10 w-10 rounded-xl object-cover"/> : <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[var(--bg-surface)] text-[var(--accent)]"><UserRound className="h-4 w-4"/></span>}<div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[var(--text-primary)]">{account.name || account.email}</p><p className="mt-1 text-[10px] capitalize text-[var(--text-muted)]">{account.role || 'customer'} · {dateTime(account.createdAt)}</p></div></motion.article>; }
function RecentNotification({ notification, index }) { return <motion.article initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * 0.04 }} className={`flex gap-3 rounded-2xl p-3 ${notification.isRead ? 'bg-[var(--bg-muted)]' : 'bg-[var(--accent-soft)]'}`}><Bell className="mt-1 h-4 w-4 shrink-0 text-[var(--accent)]"/><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-semibold text-[var(--text-primary)]">{notification.title}</p>{!notification.isRead && <span className="h-2 w-2 rounded-full bg-red-500" aria-label="Unread"/>}</div><p className="mt-1 line-clamp-1 text-xs text-[var(--text-muted)]">{notification.message}</p></div></motion.article>; }
function RecentReview({ review, index }) { return <motion.article initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * 0.04 }} className="rounded-2xl bg-[var(--bg-muted)] p-3"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-semibold text-[var(--text-primary)]">{review.customer?.name || 'Customer'} · {review.food?.name || 'Food'}</p><span className="flex items-center gap-1 text-xs font-bold text-amber-500"><Star className="h-3.5 w-3.5 fill-current"/>{review.rating || 0}</span></div><p className="mt-1 text-[10px] text-[var(--text-muted)]">Chef: {review.chef?.name || review.chef?.email || 'Unknown'}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-[var(--text-secondary)]">{review.comment || 'No comment provided.'}</p></motion.article>; }
function QuickActions() { const actions = [{ label: 'Manage Users', to: '/dashboard/admin/users', icon: Users },{ label: 'Approve Chefs', to: '/dashboard/admin/chef-verification', icon: ChefHat },{ label: 'Manage Orders', to: '/dashboard/admin/orders', icon: ReceiptText },{ label: 'Manage Foods', to: '/dashboard/admin/foods', icon: Utensils },{ label: 'Coupons', to: '/dashboard/admin/coupons', icon: TicketPercent },{ label: 'Gift Cards', to: '/dashboard/admin/gift-cards', icon: Gift },{ label: 'Platform Settings', to: '/dashboard/admin/platform-settings', icon: Settings },{ label: 'Send Notification', to: '/dashboard/admin/notifications', icon: Mail }]; return <section><SectionHeading title="Quick Actions" description="Jump directly to common administrative workflows."/><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{actions.map((action, index) => { const Icon = action.icon; return <motion.div key={action.label} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.035 }} whileHover={{ y: -4 }} whileTap={{ scale: 0.98 }}><Link to={action.to} className="flex items-center gap-4 rounded-[1.5rem] border border-[var(--border)] bg-[var(--bg-surface)] p-5 shadow-lg shadow-black/5 hover:border-[var(--accent)]"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><Icon className="h-5 w-5"/></span><span className="font-semibold text-[var(--text-primary)]">{action.label}</span></Link></motion.div>; })}</div></section>; }
function PlatformHealth({ health, connected, firebaseOnline }) { const services = [{ label: 'Backend', online: health.backend, icon: Server },{ label: 'MongoDB', online: health.mongodb, icon: Database },{ label: 'Firebase', online: firebaseOnline, icon: ShieldCheck },{ label: 'Stripe', online: health.stripe, icon: WalletCards },{ label: 'Socket.IO', online: connected, icon: Wifi }]; return <section><SectionHeading title="Platform Health" description={`Last sync: ${dateTime(health.lastSync)}`}/><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{services.map((service, index) => { const Icon = service.icon; return <motion.article key={service.label} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.04 }} className="rounded-[1.5rem] border border-[var(--border)] bg-[var(--bg-surface)] p-5"><div className="flex items-center justify-between"><Icon className="h-5 w-5 text-[var(--accent)]"/><span className={`h-2.5 w-2.5 rounded-full ${service.online ? 'bg-emerald-500' : 'bg-red-500'}`}/></div><p className="mt-4 text-sm font-semibold text-[var(--text-primary)]">{service.label}</p><p className={`mt-1 text-xs font-semibold ${service.online ? 'text-emerald-500' : 'text-red-500'}`}>{service.online ? 'Online' : 'Offline'}</p></motion.article>; })}</div></section>; }
function FooterSummary() { return <footer className="grid gap-3 rounded-[1.5rem] border border-[var(--border)] bg-[var(--bg-surface)] p-5 text-xs text-[var(--text-muted)] sm:grid-cols-3"><p><strong className="text-[var(--text-primary)]">Total Active Sessions:</strong> Coming Soon</p><p><strong className="text-[var(--text-primary)]">System Version:</strong> HomeBite 1.0.0</p><p><strong className="text-[var(--text-primary)]">Last Backup:</strong> Coming Soon</p></footer>; }
function Empty({ text }) { return <div className="rounded-2xl border border-dashed border-[var(--border)] px-5 py-12 text-center text-sm text-[var(--text-muted)]">{text}</div>; }
function OverviewSkeleton() { return <div className="mx-auto max-w-[1600px] space-y-8" role="status" aria-label="Loading admin overview"><div className="h-16 w-72 animate-pulse rounded-2xl bg-[var(--bg-muted)]"/><div className="h-60 animate-pulse rounded-[2rem] bg-[var(--bg-muted)]"/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{Array.from({ length: 6 }, (_, index) => <div key={index} className="h-44 animate-pulse rounded-3xl bg-[var(--bg-muted)]"/>)}</div><div className="grid gap-6 xl:grid-cols-2"><div className="h-96 animate-pulse rounded-[2rem] bg-[var(--bg-muted)]"/><div className="h-96 animate-pulse rounded-[2rem] bg-[var(--bg-muted)]"/></div></div>; }
