import { useQuery } from '@tanstack/react-query';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowRight, BookOpen, CalendarDays, ChevronLeft, ChevronRight, Clock3, Eye, Search, Sparkles, TrendingUp, UserRound } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import ReactPaginate from 'react-paginate';
import Skeleton, { SkeletonTheme } from 'react-loading-skeleton';
import 'react-loading-skeleton/dist/skeleton.css';
import { CATEGORY_NAMES } from '../data/categoryCatalog';
import emptyImage from '../assets/categories/traditional-meals.jpg';
import { getBlogs } from '../services/blogsApi';

const PAGE_SIZE = 6;
const date = (value) => value ? new Intl.DateTimeFormat('en-BD', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)) : 'Recently';
const blogPath = (blog) => `/blogs/${blog.slug || blog._id?.$oid || blog._id}`;

export default function Blogs() {
  const [draft, setDraft] = useState('');
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('all');
  const [sort, setSort] = useState('latest');
  const [page, setPage] = useState(1);
  const query = useQuery({
    queryKey: ['blogs', { search, category, sort, page }],
    queryFn: async () => (await getBlogs({ search: search || undefined, category: category === 'all' ? undefined : category, sort, page, limit: PAGE_SIZE })).data.data,
    placeholderData: (previous) => previous
  });
  const data = query.data || { articles: [], popular: [], featured: null, pagination: { page: 1, total: 0, totalPages: 1 } };

  function submitSearch(event) { event.preventDefault(); setSearch(draft.trim()); setPage(1); }
  function chooseCategory(value) { setCategory(value); setPage(1); }
  function chooseSort(value) { setSort(value); setPage(1); }

  return <main className="min-h-screen bg-[var(--bg-page)] pb-24 pt-24 sm:pt-28">
    <BlogHero draft={draft} setDraft={setDraft} onSubmit={submitSearch} searching={query.isFetching}/>
    <div className="container py-12 sm:py-16">
      {query.isLoading ? <BlogPageSkeleton/> : query.isError ? <ErrorState onRetry={query.refetch} busy={query.isFetching}/> : <>
        {data.featured && <FeaturedBlog blog={data.featured}/>} 
        <CategoryFilters selected={category} onSelect={chooseCategory}/>
        <PopularMobile blogs={data.popular || []}/>
        <div className="mt-12 grid items-start gap-8 lg:grid-cols-[minmax(0,1fr)_330px]">
          <section aria-labelledby="latest-articles-title"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-[var(--accent)]">Food & community</p><h2 id="latest-articles-title" className="mt-2 text-3xl font-semibold text-[var(--text-primary)]">Latest Articles</h2></div><div className="flex rounded-full border border-[var(--border)] bg-[var(--bg-surface)] p-1" aria-label="Sort articles">{[['latest','Latest'],['popular','Popular']].map(([value, label]) => <button key={value} type="button" onClick={() => chooseSort(value)} aria-pressed={sort === value} className={`rounded-full px-4 py-2 text-xs font-semibold transition ${sort === value ? 'bg-[var(--accent)] text-white' : 'text-[var(--text-secondary)] hover:text-[var(--accent)]'}`}>{label}</button>)}</div></div>
            {data.articles?.length ? <motion.div layout initial="hidden" animate="show" variants={{ hidden: {}, show: { transition: { staggerChildren: 0.06 } } }} className="grid gap-6 md:grid-cols-2"><AnimatePresence mode="popLayout">{data.articles.map((blog) => <ArticleCard key={blog._id?.$oid || blog._id} blog={blog}/>)}</AnimatePresence></motion.div> : <EmptyState onReset={() => { setDraft(''); setSearch(''); setCategory('all'); setSort('latest'); setPage(1); }}/>} 
            {data.pagination?.totalPages > 1 && <Pagination page={page} totalPages={data.pagination.totalPages} onPage={setPage}/>} 
          </section>
          <PopularSidebar blogs={data.popular || []}/>
        </div>
      </>}
    </div>
  </main>;
}

function BlogHero({ draft, setDraft, onSubmit, searching }) { return <section className="relative isolate overflow-hidden border-b border-[var(--border)]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_20%,rgba(249,115,22,0.18),transparent_30%),radial-gradient(circle_at_85%_35%,rgba(139,92,246,0.13),transparent_28%)]"/><motion.div animate={{ x: [0, 18, 0], y: [0, -12, 0] }} transition={{ duration: 10, repeat: Infinity }} className="absolute -left-24 top-8 h-72 w-72 rounded-full bg-orange-500/10 blur-3xl"/><div className="container relative py-20 text-center sm:py-24"><motion.div initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} className="mx-auto max-w-4xl"><span className="inline-flex items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--bg-surface)] px-4 py-2 text-xs font-bold uppercase tracking-[0.22em] text-[var(--accent)]"><BookOpen className="h-4 w-4"/>HomeBite Journal</span><h1 className="mt-7 text-4xl font-semibold tracking-[-0.04em] text-[var(--text-primary)] sm:text-6xl">Discover Stories, Recipes & Food Inspiration</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-8 text-[var(--text-secondary)] sm:text-lg">Meet local chefs, explore meaningful food traditions, and find practical inspiration for every homemade meal.</p><form onSubmit={onSubmit} className="mx-auto mt-9 flex max-w-2xl items-center gap-3 rounded-full border border-[var(--border)] bg-[var(--bg-surface)] p-2 shadow-[var(--shadow-soft)]" role="search"><Search className="ml-3 h-5 w-5 shrink-0 text-[var(--text-muted)]"/><label className="sr-only" htmlFor="blog-search">Search articles</label><input id="blog-search" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Search titles, categories, or tags..." className="min-w-0 flex-1 bg-transparent py-3 text-sm text-[var(--text-primary)] outline-none"/><motion.button whileTap={{ scale: 0.97 }} type="submit" disabled={searching} className="shrink-0 rounded-full bg-gradient-to-r from-orange-500 to-rose-500 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{searching ? 'Searching...' : 'Search'}</motion.button></form></motion.div></div></section>; }
function FeaturedBlog({ blog }) { return <motion.section initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} aria-labelledby="featured-blog-title" className="overflow-hidden rounded-[2.25rem] border border-[var(--border)] bg-[var(--bg-surface)] shadow-[var(--shadow-elevated)]"><div className="grid lg:grid-cols-[1.15fr_0.85fr]"><Link to={blogPath(blog)} className="group block min-h-72 overflow-hidden focus:outline-none focus-visible:ring-4 focus-visible:ring-inset focus-visible:ring-[var(--accent-soft)]">{blog.coverImage ? <img src={blog.coverImage} alt={blog.title} className="h-full min-h-72 w-full object-cover transition duration-700 group-hover:scale-105"/> : <div className="flex h-full min-h-72 items-center justify-center bg-[var(--bg-muted)]"><BookOpen className="h-12 w-12 text-[var(--accent)]"/></div>}</Link><div className="flex flex-col justify-center p-6 sm:p-9"><span className="inline-flex w-fit items-center gap-2 rounded-full bg-[var(--accent-soft)] px-3 py-1.5 text-xs font-semibold text-[var(--accent)]"><Sparkles className="h-3.5 w-3.5"/>Featured · {blog.category}</span><h2 id="featured-blog-title" className="mt-5 text-3xl font-semibold tracking-tight text-[var(--text-primary)]">{blog.title}</h2><p className="mt-4 line-clamp-3 text-sm leading-7 text-[var(--text-secondary)]">{blog.excerpt}</p><AuthorMeta blog={blog} className="mt-6"/><Link to={blogPath(blog)} className="mt-7 inline-flex w-fit items-center gap-2 rounded-full bg-[var(--accent)] px-5 py-3 text-sm font-semibold text-white focus:outline-none focus-visible:ring-4 focus-visible:ring-[var(--accent-soft)]">Read More <ArrowRight className="h-4 w-4"/></Link></div></div></motion.section>; }
function CategoryFilters({ selected, onSelect }) { return <section className="mt-12" aria-labelledby="blog-categories-title"><h2 id="blog-categories-title" className="sr-only">Blog categories</h2><div className="flex gap-2 overflow-x-auto pb-2">{['all', ...CATEGORY_NAMES].map((item) => <button key={item} type="button" onClick={() => onSelect(item)} aria-pressed={selected === item} className={`shrink-0 rounded-full border px-4 py-2.5 text-xs font-semibold transition focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-soft)] ${selected === item ? 'border-[var(--accent)] bg-[var(--accent)] text-white' : 'border-[var(--border)] bg-[var(--bg-surface)] text-[var(--text-secondary)] hover:border-[var(--accent)] hover:text-[var(--accent)]'}`}>{item === 'all' ? 'All Articles' : item}</button>)}</div></section>; }
function ArticleCard({ blog }) { return <motion.article layout variants={{ hidden: { opacity: 0, y: 18 }, show: { opacity: 1, y: 0 } }} exit={{ opacity: 0, scale: 0.97 }} whileHover={{ y: -6 }} className="group overflow-hidden rounded-[1.75rem] border border-[var(--border)] bg-[var(--bg-surface)] shadow-lg shadow-black/5"><Link to={blogPath(blog)} className="block aspect-[16/10] overflow-hidden bg-[var(--bg-muted)] focus:outline-none focus-visible:ring-4 focus-visible:ring-inset focus-visible:ring-[var(--accent-soft)]">{blog.coverImage ? <img src={blog.coverImage} alt={blog.title} loading="lazy" decoding="async" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/> : <span className="flex h-full items-center justify-center"><BookOpen className="h-9 w-9 text-[var(--accent)]"/></span>}</Link><div className="p-5"><span className="inline-flex rounded-full bg-[var(--accent-soft)] px-3 py-1 text-[10px] font-bold text-[var(--accent)]">{blog.category || 'Food Stories'}</span><h3 className="mt-4 line-clamp-2 text-xl font-semibold text-[var(--text-primary)]"><Link to={blogPath(blog)} className="focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-soft)]">{blog.title}</Link></h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-[var(--text-secondary)]">{blog.excerpt}</p><AuthorMeta blog={blog} className="mt-5"/><div className="mt-5 flex items-center justify-between border-t border-[var(--border)] pt-4"><span className="inline-flex items-center gap-1.5 text-xs text-[var(--text-muted)]"><Eye className="h-3.5 w-3.5"/>{Number(blog.views || 0).toLocaleString()} views</span><Link to={blogPath(blog)} className="inline-flex items-center gap-1.5 text-xs font-semibold text-[var(--accent)] focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-soft)]">Read More <ArrowRight className="h-3.5 w-3.5"/></Link></div></div></motion.article>; }
function AuthorMeta({ blog, className = '' }) { return <div className={`flex items-center gap-3 ${className}`}>{blog.authorImage ? <img src={blog.authorImage} alt="" loading="lazy" className="h-9 w-9 rounded-xl object-cover"/> : <span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[var(--bg-muted)] text-[var(--accent)]"><UserRound className="h-4 w-4"/></span>}<div className="min-w-0"><p className="truncate text-xs font-semibold text-[var(--text-primary)]">{blog.authorName || 'HomeBite Editorial'}</p><p className="mt-1 flex flex-wrap items-center gap-2 text-[10px] text-[var(--text-muted)]"><span className="inline-flex items-center gap-1"><Clock3 className="h-3 w-3"/>{blog.readTime || '5 min read'}</span><span>·</span><span className="inline-flex items-center gap-1"><CalendarDays className="h-3 w-3"/>{date(blog.publishedAt)}</span></p></div></div>; }
function PopularSidebar({ blogs }) { return <aside className="sticky top-28 hidden rounded-[1.75rem] border border-[var(--border)] bg-[var(--bg-surface)] p-5 shadow-lg shadow-black/5 lg:block" aria-labelledby="popular-title"><div className="flex items-center gap-3"><TrendingUp className="h-5 w-5 text-[var(--accent)]"/><h2 id="popular-title" className="text-lg font-semibold text-[var(--text-primary)]">Popular Articles</h2></div><div className="mt-5 space-y-4">{blogs.length ? blogs.map((blog, index) => <PopularItem key={blog._id?.$oid || blog._id} blog={blog} index={index}/>) : <p className="py-8 text-center text-sm text-[var(--text-muted)]">Popular stories will appear here.</p>}</div></aside>; }
function PopularMobile({ blogs }) { if (!blogs.length) return null; return <section className="mt-10 lg:hidden" aria-labelledby="popular-mobile-title"><div className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-[var(--accent)]"/><h2 id="popular-mobile-title" className="text-lg font-semibold text-[var(--text-primary)]">Popular Articles</h2></div><div className="mt-4 flex snap-x gap-4 overflow-x-auto pb-3">{blogs.map((blog, index) => <div key={blog._id?.$oid || blog._id} className="w-[82vw] max-w-sm shrink-0 snap-start rounded-2xl border border-[var(--border)] bg-[var(--bg-surface)] p-4"><PopularItem blog={blog} index={index}/></div>)}</div></section>; }
function PopularItem({ blog, index }) { return <motion.article initial={{ opacity: 0, x: 10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * 0.04 }}><Link to={blogPath(blog)} className="group flex gap-3 rounded-xl focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-soft)]">{blog.coverImage ? <img src={blog.coverImage} alt="" loading="lazy" className="h-20 w-24 shrink-0 rounded-xl object-cover transition group-hover:scale-[1.03]"/> : <span className="flex h-20 w-24 shrink-0 items-center justify-center rounded-xl bg-[var(--bg-muted)]"><BookOpen className="h-5 w-5 text-[var(--accent)]"/></span>}<span className="min-w-0"><span className="text-[10px] font-bold uppercase tracking-wider text-[var(--accent)]">#{index + 1} · {blog.category}</span><span className="mt-2 line-clamp-2 block text-sm font-semibold leading-5 text-[var(--text-primary)]">{blog.title}</span><span className="mt-2 flex items-center gap-1 text-[10px] text-[var(--text-muted)]"><Eye className="h-3 w-3"/>{Number(blog.views || 0).toLocaleString()}</span></span></Link></motion.article>; }
function Pagination({ page, totalPages, onPage }) { return <nav className="mt-10" aria-label="Blog pagination"><ReactPaginate pageCount={totalPages} forcePage={page - 1} onPageChange={({ selected }) => { onPage(selected + 1); window.scrollTo({ top: 500, behavior: 'smooth' }); }} previousLabel={<ChevronLeft className="h-4 w-4"/>} nextLabel={<ChevronRight className="h-4 w-4"/>} breakLabel="…" containerClassName="flex flex-wrap items-center justify-center gap-2" pageLinkClassName="flex h-10 min-w-10 items-center justify-center rounded-full border border-[var(--border)] px-3 text-sm font-semibold text-[var(--text-secondary)] hover:border-[var(--accent)] hover:text-[var(--accent)] focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-soft)]" activeLinkClassName="!border-[var(--accent)] !bg-[var(--accent)] !text-white" previousLinkClassName="flex h-10 w-10 items-center justify-center rounded-full border border-[var(--border)] text-[var(--text-secondary)]" nextLinkClassName="flex h-10 w-10 items-center justify-center rounded-full border border-[var(--border)] text-[var(--text-secondary)]" disabledLinkClassName="pointer-events-none opacity-35"/></nav>; }
function BlogPageSkeleton() { return <SkeletonTheme baseColor="var(--bg-muted)" highlightColor="var(--bg-surface)"><div role="status" aria-label="Loading blog articles" className="space-y-12"><Skeleton height={420} borderRadius={36}/><div className="flex gap-2 overflow-hidden">{Array.from({ length: 6 }, (_, index) => <Skeleton key={index} width={130} height={38} borderRadius={999}/>)}</div><div className="grid gap-6 lg:grid-cols-[1fr_330px]"><div className="grid gap-6 md:grid-cols-2">{Array.from({ length: 6 }, (_, index) => <div key={index}><Skeleton height={220} borderRadius={28}/><Skeleton count={3} className="mt-3"/></div>)}</div><Skeleton height={520} borderRadius={28}/></div></div></SkeletonTheme>; }
function ErrorState({ onRetry, busy }) { return <div className="rounded-[2rem] border border-red-500/20 bg-red-500/5 px-6 py-20 text-center"><BookOpen className="mx-auto h-10 w-10 text-red-500"/><h2 className="mt-5 text-xl font-semibold text-[var(--text-primary)]">The journal could not be loaded</h2><button type="button" onClick={onRetry} disabled={busy} className="mt-6 rounded-full border border-red-500/20 px-6 py-3 text-sm font-semibold text-red-500 disabled:opacity-50">{busy ? 'Retrying...' : 'Retry'}</button></div>; }
function EmptyState({ onReset }) { return <motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="rounded-[2rem] border border-dashed border-[var(--border)] bg-[var(--bg-surface)] px-6 py-16 text-center"><img src={emptyImage} alt="Homemade food prepared for a future story" className="mx-auto h-40 w-64 rounded-[1.75rem] object-cover shadow-[var(--shadow-soft)]"/><h2 className="mt-6 text-2xl font-semibold text-[var(--text-primary)]">No stories found</h2><p className="mx-auto mt-3 max-w-md text-sm leading-7 text-[var(--text-secondary)]">Try a different search or category while our community prepares more food stories.</p><button type="button" onClick={onReset} className="mt-6 rounded-full bg-[var(--accent)] px-6 py-3 text-sm font-semibold text-white">Browse All Articles</button></motion.div>; }
