import { useQuery } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, AtSign, BookOpen, Briefcase, CalendarDays, Clock3, Copy, Eye, Link2, Mail, Share2, UserRound, Users } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import toast from 'react-hot-toast';
import ReactMarkdown from 'react-markdown';
import { Link, useParams } from 'react-router-dom';
import Skeleton, { SkeletonTheme } from 'react-loading-skeleton';
import remarkGfm from 'remark-gfm';
import { getBlogBySlug } from '../services/blogsApi';

const formatDate = (value) => value ? new Intl.DateTimeFormat('en-BD', { month: 'long', day: 'numeric', year: 'numeric' }).format(new Date(value)) : 'Recently';
const blogPath = (blog) => `/blogs/${blog?.slug || blog?._id?.$oid || blog?._id}`;
const headingId = (value) => String(value || '').toLowerCase().replace(/[*_`~#[\]()]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const readingTime = (blog) => blog?.readTime || `${Math.max(1, Math.ceil(String(blog?.content || '').split(/\s+/).filter(Boolean).length / 200))} min read`;

export default function BlogDetails() {
  const { slug } = useParams();
  const articleRef = useRef(null);
  const [progress, setProgress] = useState(0);
  const query = useQuery({ queryKey: ['blog', slug], queryFn: async () => (await getBlogBySlug(slug)).data.data, staleTime: 0, refetchOnMount: 'always', retry: (count, error) => error.response?.status !== 404 && count < 1 });

  useEffect(() => {
    let frame;
    function update() {
      if (frame) cancelAnimationFrame(frame);
      frame = requestAnimationFrame(() => {
        const article = articleRef.current;
        if (!article) return;
        const rect = article.getBoundingClientRect();
        const start = window.scrollY + rect.top - 120;
        const distance = Math.max(1, article.offsetHeight - window.innerHeight + 160);
        setProgress(Math.min(100, Math.max(0, ((window.scrollY - start) / distance) * 100)));
      });
    }
    update(); window.addEventListener('scroll', update, { passive: true }); window.addEventListener('resize', update);
    return () => { window.removeEventListener('scroll', update); window.removeEventListener('resize', update); if (frame) cancelAnimationFrame(frame); };
  }, [query.data]);

  if (query.isLoading) return <DetailsSkeleton/>;
  if (query.isError && query.error.response?.status === 404) return <BlogNotFound/>;
  if (query.isError) return <LoadError onRetry={query.refetch} busy={query.isFetching}/>;
  const { blog, related = [], previous, next } = query.data;
  const toc = extractHeadings(blog.content);

  return <main className="min-h-screen bg-[var(--bg-page)] pb-24 pt-24 sm:pt-28">
    <ReadingProgress value={progress}/>
    <article ref={articleRef}>
      <header className="container py-10 sm:py-14"><Link to="/blogs" className="inline-flex items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--bg-surface)] px-4 py-2.5 text-sm font-semibold text-[var(--text-secondary)] focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-soft)]"><ArrowLeft className="h-4 w-4"/>Back to Blogs</Link><motion.div initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} className="mx-auto mt-10 max-w-5xl text-center"><span className="inline-flex rounded-full bg-[var(--accent-soft)] px-4 py-2 text-xs font-bold uppercase tracking-[0.18em] text-[var(--accent)]">{blog.category || 'Food Stories'}</span><h1 className="mt-6 text-4xl font-semibold tracking-[-0.04em] text-[var(--text-primary)] sm:text-6xl lg:text-7xl">{blog.title}</h1><p className="mx-auto mt-6 max-w-3xl text-base leading-8 text-[var(--text-secondary)] sm:text-xl">{blog.excerpt}</p><AuthorHeader blog={blog}/><ShareButtons title={blog.title}/></motion.div></header>
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="container"><div className="group relative mx-auto max-w-7xl overflow-hidden rounded-[2.5rem] bg-[var(--bg-muted)] shadow-[var(--shadow-elevated)]">{blog.coverImage ? <img src={blog.coverImage} alt={blog.title} className="max-h-[720px] min-h-72 w-full object-cover transition duration-700 group-hover:scale-[1.02]"/> : <span className="flex min-h-[420px] items-center justify-center"><BookOpen className="h-16 w-16 text-[var(--accent)]"/></span>}<div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/15 to-transparent"/></div></motion.div>
      <div className="container mt-14 grid items-start gap-10 lg:grid-cols-[250px_minmax(0,760px)_70px] lg:justify-center">
        <TableOfContents headings={toc}/>
        <ArticleContent content={blog.content || ''}/>
        <div className="sticky top-32 hidden justify-center lg:flex"><ShareRail title={blog.title}/></div>
      </div>
    </article>
    <div className="container mt-16 max-w-5xl"><PreviousNext previous={previous} next={next}/><Newsletter/><RelatedArticles blogs={related}/><div className="mt-12 text-center"><Link to="/blogs" className="inline-flex items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--bg-surface)] px-6 py-3 text-sm font-semibold text-[var(--text-primary)] focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-soft)]"><ArrowLeft className="h-4 w-4"/>Back to Blogs</Link></div></div>
  </main>;
}

function ReadingProgress({ value }) { return <div className="fixed inset-x-0 top-0 z-[200] h-1 bg-transparent" aria-hidden="true"><motion.div className="h-full origin-left bg-gradient-to-r from-orange-500 to-rose-500" animate={{ width: `${value}%` }} transition={{ duration: 0.1 }}/></div>; }
function AuthorHeader({ blog }) { return <div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">{blog.authorImage ? <img src={blog.authorImage} alt={`${blog.authorName || 'Author'} profile`} className="h-12 w-12 rounded-2xl object-cover"/> : <span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[var(--bg-muted)] text-[var(--accent)]"><UserRound className="h-5 w-5"/></span>}<div className="text-center sm:text-left"><p className="text-sm font-semibold text-[var(--text-primary)]">{blog.authorName || 'HomeBite Editorial'}</p><p className="mt-1 flex flex-wrap items-center justify-center gap-3 text-xs text-[var(--text-muted)] sm:justify-start"><span className="inline-flex items-center gap-1"><CalendarDays className="h-3.5 w-3.5"/>{formatDate(blog.publishedAt)}</span><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5"/>{readingTime(blog)}</span><span className="inline-flex items-center gap-1"><Eye className="h-3.5 w-3.5"/>{Number(blog.views || 0).toLocaleString()} views</span></p></div></div>; }
function ShareButtons({ title }) { return <div className="mt-7 flex flex-wrap justify-center gap-2" aria-label="Share this article"><ShareButton platform="facebook" title={title} icon={Users} label="Facebook"/><ShareButton platform="x" title={title} icon={AtSign} label="X"/><ShareButton platform="linkedin" title={title} icon={Briefcase} label="LinkedIn"/><ShareButton platform="copy" title={title} icon={Copy} label="Copy Link"/></div>; }
function ShareRail({ title }) { return <div className="space-y-2" aria-label="Share article"><ShareButton platform="facebook" title={title} icon={Users}/><ShareButton platform="x" title={title} icon={AtSign}/><ShareButton platform="linkedin" title={title} icon={Briefcase}/><ShareButton platform="copy" title={title} icon={Link2}/></div>; }
function ShareButton({ platform, title, icon: Icon, label }) { async function share() { const url = window.location.href; if (platform === 'copy') { try { await navigator.clipboard.writeText(url); toast.success('Article link copied.'); } catch { toast.error('Unable to copy the link.'); } return; } const destinations = { facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`, x: `https://twitter.com/intent/tweet?url=${encodeURIComponent(url)}&text=${encodeURIComponent(title)}`, linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}` }; window.open(destinations[platform], '_blank', 'noopener,noreferrer,width=720,height=600'); } return <motion.button whileHover={{ y: -2 }} whileTap={{ scale: 0.94 }} type="button" onClick={share} aria-label={`Share on ${label || platform}`} className={`inline-flex h-10 items-center justify-center gap-2 rounded-full border border-[var(--border)] bg-[var(--bg-surface)] text-xs font-semibold text-[var(--text-secondary)] transition hover:border-[var(--accent)] hover:text-[var(--accent)] ${label ? 'px-4' : 'w-10'}`}><Icon className="h-4 w-4"/>{label}</motion.button>; }
function extractHeadings(content) { const headings = []; String(content || '').replace(/^(#{2,3})\s+(.+)$/gm, (_, marks, text) => { const clean = text.replace(/[*_`~]/g, '').trim(); headings.push({ level: marks.length, text: clean, id: headingId(clean) }); return _; }); return headings; }
function TableOfContents({ headings }) { if (!headings.length) return <aside className="hidden lg:block"/>; return <aside className="sticky top-28 hidden max-h-[calc(100vh-8rem)] overflow-y-auto lg:block" aria-labelledby="toc-title"><p id="toc-title" className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--accent)]">Table of Contents</p><nav className="mt-4 border-l border-[var(--border)] pl-4">{headings.map((heading, index) => <a key={`${heading.id}-${index}`} href={`#${heading.id}`} className={`block py-2 text-xs leading-5 text-[var(--text-muted)] transition hover:text-[var(--accent)] focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-soft)] ${heading.level === 3 ? 'pl-3' : 'font-semibold'}`}>{heading.text}</a>)}</nav></aside>; }
function ArticleContent({ content }) { const heading = (Tag) => function Heading({ children }) { const text = String(children); return <Tag id={headingId(text)} className={`${Tag === 'h2' ? 'mb-4 mt-12 text-3xl sm:text-4xl' : 'mb-3 mt-9 text-2xl sm:text-3xl'} scroll-mt-28 font-semibold tracking-tight text-[var(--text-primary)]`}>{children}</Tag>; }; return <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="min-w-0"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{ h1: heading('h2'), h2: heading('h2'), h3: heading('h3'), p({ node, children }) { const only = node?.children?.length === 1 ? node.children[0] : null; const videoId = only?.type === 'link' ? youtubeId(only.url) : null; return videoId ? <YouTubeEmbed id={videoId}/> : <p className="my-6 text-base leading-8 text-[var(--text-secondary)] sm:text-lg sm:leading-9">{children}</p>; }, ul: ({ children }) => <ul className="my-6 list-disc space-y-2 pl-6 text-base leading-8 text-[var(--text-secondary)] sm:text-lg">{children}</ul>, ol: ({ children }) => <ol className="my-6 list-decimal space-y-2 pl-6 text-base leading-8 text-[var(--text-secondary)] sm:text-lg">{children}</ol>, blockquote: ({ children }) => <blockquote className="my-8 rounded-r-2xl border-l-4 border-[var(--accent)] bg-[var(--accent-soft)] px-6 py-4 text-lg italic leading-8 text-[var(--text-primary)]">{children}</blockquote>, img: ({ src, alt }) => <img src={src} alt={alt || ''} loading="lazy" decoding="async" className="my-9 max-h-[620px] w-full rounded-[1.75rem] object-cover shadow-[var(--shadow-soft)]"/>, a: ({ href, children }) => <a href={href} target={href?.startsWith('http') ? '_blank' : undefined} rel={href?.startsWith('http') ? 'noopener noreferrer' : undefined} className="font-semibold text-[var(--accent)] underline decoration-orange-500/30 underline-offset-4">{children}</a>, code: ({ className, children }) => className ? <code className="block overflow-x-auto rounded-2xl bg-slate-950 p-5 font-mono text-sm leading-7 text-slate-100">{children}</code> : <code className="rounded bg-[var(--bg-muted)] px-1.5 py-0.5 font-mono text-sm text-[var(--accent)]">{children}</code>, pre: ({ children }) => <pre className="my-8 overflow-x-auto rounded-2xl bg-slate-950">{children}</pre>, hr: () => <hr className="my-12 border-[var(--border)]"/>, table: ({ children }) => <div className="my-8 overflow-x-auto"><table className="w-full border-collapse text-left text-sm">{children}</table></div>, th: ({ children }) => <th className="border border-[var(--border)] bg-[var(--bg-muted)] p-3 text-[var(--text-primary)]">{children}</th>, td: ({ children }) => <td className="border border-[var(--border)] p-3 text-[var(--text-secondary)]">{children}</td> }}>{content}</ReactMarkdown></motion.div>; }
function youtubeId(url) { try { const parsed = new URL(url); if (parsed.hostname.includes('youtu.be')) return parsed.pathname.slice(1); if (parsed.hostname.includes('youtube.com')) return parsed.searchParams.get('v') || parsed.pathname.split('/').filter(Boolean).pop(); } catch { return null; } return null; }
function YouTubeEmbed({ id }) { return <div className="my-9 aspect-video overflow-hidden rounded-[1.75rem] border border-[var(--border)] shadow-[var(--shadow-soft)]"><iframe src={`https://www.youtube-nocookie.com/embed/${id}`} title="Embedded YouTube video" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen className="h-full w-full"/></div>; }
function PreviousNext({ previous, next }) { if (!previous && !next) return null; return <nav aria-label="Article navigation" className="grid gap-4 sm:grid-cols-2">{previous ? <ArticleNav article={previous} direction="previous"/> : <div/>}{next && <ArticleNav article={next} direction="next"/>}</nav>; }
function ArticleNav({ article, direction }) { const previous = direction === 'previous'; return <motion.div whileHover={{ y: -3 }}><Link to={blogPath(article)} className={`flex h-full items-center gap-4 rounded-[1.5rem] border border-[var(--border)] bg-[var(--bg-surface)] p-5 shadow-lg shadow-black/5 focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-soft)] ${previous ? '' : 'text-right sm:justify-end'}`}>{previous && <ArrowLeft className="h-5 w-5 shrink-0 text-[var(--accent)]"/>}<span className="min-w-0"><span className="text-[10px] font-bold uppercase tracking-wider text-[var(--text-muted)]">{previous ? 'Previous Article' : 'Next Article'}</span><span className="mt-2 line-clamp-2 block text-sm font-semibold text-[var(--text-primary)]">{article.title}</span></span>{!previous && <ArrowRight className="h-5 w-5 shrink-0 text-[var(--accent)]"/>}</Link></motion.div>; }
function Newsletter() { function submit(event) { event.preventDefault(); toast('Newsletter subscriptions are coming soon.'); } return <motion.section initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="relative mt-12 overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-violet-950 to-orange-950 p-7 text-white sm:p-10"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-orange-500/20 blur-3xl"/><div className="relative grid items-center gap-7 md:grid-cols-[1fr_0.9fr]"><div><Mail className="h-7 w-7 text-orange-300"/><h2 className="mt-4 text-3xl font-semibold text-white">Fresh stories, served weekly</h2><p className="mt-3 text-sm leading-7 text-white/70">Get recipes, chef stories, and community inspiration delivered to your inbox.</p></div><form onSubmit={submit} className="flex rounded-full border border-white/15 bg-white/10 p-2"><label htmlFor="article-newsletter-email" className="sr-only">Email address</label><input id="article-newsletter-email" type="email" required placeholder="you@example.com" className="min-w-0 flex-1 bg-transparent px-4 text-sm text-white outline-none placeholder:text-white/45"/><button type="submit" className="rounded-full bg-white px-5 py-3 text-sm font-semibold text-violet-800">Subscribe</button></form></div></motion.section>; }
function RelatedArticles({ blogs }) { if (!blogs.length) return null; return <section className="mt-16" aria-labelledby="related-title"><h2 id="related-title" className="text-3xl font-semibold text-[var(--text-primary)]">Related Articles</h2><motion.div initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.15 }} variants={{ hidden: {}, show: { transition: { staggerChildren: 0.07 } } }} className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{blogs.map((blog) => <motion.article key={blog._id?.$oid || blog._id} variants={{ hidden: { opacity: 0, y: 15 }, show: { opacity: 1, y: 0 } }} whileHover={{ y: -5 }} className="group overflow-hidden rounded-[1.5rem] border border-[var(--border)] bg-[var(--bg-surface)]"><Link to={blogPath(blog)} className="block focus:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[var(--accent-soft)]">{blog.coverImage ? <img src={blog.coverImage} alt="" loading="lazy" className="aspect-[16/10] w-full object-cover transition duration-500 group-hover:scale-105"/> : <span className="flex aspect-[16/10] items-center justify-center bg-[var(--bg-muted)]"><BookOpen className="h-7 w-7 text-[var(--accent)]"/></span>}<span className="block p-4"><span className="text-[10px] font-bold uppercase tracking-wider text-[var(--accent)]">{blog.category}</span><span className="mt-2 line-clamp-2 block text-sm font-semibold leading-6 text-[var(--text-primary)]">{blog.title}</span><span className="mt-3 block text-[10px] text-[var(--text-muted)]">{readingTime(blog)} · {formatDate(blog.publishedAt)}</span></span></Link></motion.article>)}</motion.div></section>; }
function DetailsSkeleton() { return <main className="min-h-screen bg-[var(--bg-page)] pb-24 pt-28"><SkeletonTheme baseColor="var(--bg-muted)" highlightColor="var(--bg-surface)"><div className="container space-y-10" role="status" aria-label="Loading article"><Skeleton width={140} height={40} borderRadius={999}/><div className="mx-auto max-w-4xl text-center"><Skeleton width={120} height={28} borderRadius={999}/><Skeleton height={65} count={2} className="mt-4"/><Skeleton width={420} height={24} className="mt-5"/></div><Skeleton height={560} borderRadius={40}/><div className="mx-auto max-w-3xl"><Skeleton count={12} height={20} className="mb-3"/></div></div></SkeletonTheme></main>; }
function BlogNotFound() { return <main className="flex min-h-screen items-center justify-center bg-[var(--bg-page)] px-5 py-32"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="max-w-xl text-center"><span className="mx-auto flex h-20 w-20 items-center justify-center rounded-[1.75rem] bg-[var(--accent-soft)] text-[var(--accent)]"><BookOpen className="h-9 w-9"/></span><p className="mt-7 text-sm font-bold uppercase tracking-[0.25em] text-[var(--accent)]">404 · Article missing</p><h1 className="mt-4 text-4xl font-semibold text-[var(--text-primary)]">Blog Not Found</h1><p className="mt-4 text-base leading-8 text-[var(--text-secondary)]">This story may have moved, been unpublished, or never existed. Explore the journal for something equally delicious.</p><Link to="/blogs" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[var(--accent)] px-6 py-3.5 text-sm font-semibold text-white"><ArrowLeft className="h-4 w-4"/>Back to Blogs</Link></motion.div></main>; }
function LoadError({ onRetry, busy }) { return <main className="flex min-h-screen items-center justify-center bg-[var(--bg-page)] px-5 py-32"><div className="text-center"><h1 className="text-3xl font-semibold text-[var(--text-primary)]">The article could not be loaded</h1><button type="button" onClick={onRetry} disabled={busy} className="mt-6 rounded-full border border-red-500/20 px-6 py-3 text-sm font-semibold text-red-500 disabled:opacity-50">{busy ? 'Retrying...' : 'Retry'}</button></div></main>; }
