import { motion } from 'framer-motion';
import { Accordion, AccordionItem, AccordionItemButton, AccordionItemHeading, AccordionItemPanel } from 'react-accessible-accordion';
import CountUp from 'react-countup';
import { useInView } from 'react-intersection-observer';
import { Element, Link as ScrollLink, scroller } from 'react-scroll';
import { Link, useLocation } from 'react-router-dom';
import { ArrowRight, Bot, CheckCircle2, ChefHat, ChevronDown, CircleDollarSign, ClipboardCheck, Compass, CreditCard, Filter, Heart, HeartHandshake, Home, MapPin, Package, Search, ShieldCheck, ShoppingBag, Sparkles, Star, Truck, UserCheck, Users, UtensilsCrossed, WalletCards } from 'lucide-react';
import { useEffect, useState } from 'react';
import heroFood from '../assets/categories/family-meals.jpg';
import browseFood from '../assets/categories/healthy-meals.jpg';
import deliveryFood from '../assets/categories/traditional-meals.jpg';

const browseSteps = [
  { title: 'Browse categories', text: 'Explore collections designed around every appetite and occasion.', icon: Compass },
  { title: 'Search meals', text: 'Find a dish, cuisine, or local chef in seconds.', icon: Search },
  { title: 'Use smart filters', text: 'Narrow results by category, cuisine, price, chef, and rating.', icon: Filter },
  { title: 'View meal details', text: 'Review ingredients, nutrition, preparation time, and chef information.', icon: UtensilsCrossed },
  { title: 'Add to Wishlist', text: 'Save interesting meals and return to them from any page.', icon: Heart },
  { title: 'Add to Cart', text: 'Choose a meal and quantity when you are ready to order.', icon: ShoppingBag }
];
const orderSteps = [
  { title: 'Choose Meal', text: 'Select a homemade dish from a verified local chef.', icon: UtensilsCrossed },
  { title: 'Add To Cart', text: 'Add your preferred quantity without leaving the meal experience.', icon: ShoppingBag },
  { title: 'Review Cart', text: 'Confirm meals, quantities, prices, and your order total.', icon: ClipboardCheck },
  { title: 'Checkout', text: 'Move securely into the customer dashboard checkout.', icon: WalletCards },
  { title: 'Shipping Address', text: 'Provide the phone number and delivery address for your order.', icon: MapPin },
  { title: 'Stripe Payment', text: 'Complete card payment through Stripe’s secure payment flow.', icon: CreditCard },
  { title: 'Order Confirmation', text: 'Receive immediate confirmation after successful payment.', icon: CheckCircle2 },
  { title: 'Chef Receives Order', text: 'The intended chef is notified instantly and can accept the order.', icon: ChefHat }
];
const deliverySteps = [
  { title: 'Chef Accepts Order', text: 'Your chef confirms the order and begins the fulfillment journey.', icon: UserCheck },
  { title: 'Preparing Meal', text: 'Fresh ingredients are prepared specifically for your order.', icon: ChefHat },
  { title: 'Ready', text: 'The completed meal is packed and ready to leave the kitchen.', icon: Package },
  { title: 'Out For Delivery', text: 'Follow the live order status as the meal travels to you.', icon: Truck },
  { title: 'Delivered', text: 'Your order reaches the delivery address you provided.', icon: Home },
  { title: 'Enjoy Homemade Food', text: 'Open your meal and enjoy the comfort of authentic home cooking.', icon: Sparkles },
  { title: 'Leave Review', text: 'Rate the delivered order and help other customers discover great chefs.', icon: Star }
];
const benefits = [
  { title: 'Fresh Homemade Meals', text: 'Meals prepared in local kitchens with care and fresh ingredients.', icon: UtensilsCrossed },
  { title: 'Verified Local Chefs', text: 'Chef applications are reviewed before sellers join the marketplace.', icon: ShieldCheck },
  { title: 'Secure Stripe Payments', text: 'Card details are handled through Stripe’s secure payment experience.', icon: CreditCard },
  { title: 'Real-Time Tracking', text: 'Order status changes arrive instantly without refreshing the page.', icon: Truck },
  { title: 'Ratings & Reviews', text: 'Delivered-order reviews build transparent trust across the community.', icon: Star },
  { title: 'AI Food Assistant', text: 'Get meal ideas based on budget, cuisine, preferences, and health goals.', icon: Bot }
];
const faqs = [
  { q: 'How do I place an order?', a: 'Browse meals, add available dishes to your cart, review quantities, enter your delivery information, and complete payment at checkout.' },
  { q: 'How are payments handled?', a: 'HomeBite uses Stripe for secure card payments. An order is created only after the payment succeeds.' },
  { q: 'Can I track delivery progress?', a: 'Yes. Your order details page updates in real time as the chef accepts, prepares, readies, dispatches, and delivers the meal.' },
  { q: 'How do refunds work?', a: 'Refund tools are still being developed. Contact HomeBite support with your order and transaction details if an order requires review.' },
  { q: 'How does HomeBite support food safety?', a: 'Chef applications are reviewed, customers can inspect meal details and ingredients, and delivered orders can be rated and reviewed.' }
];

export default function HowItWorksPage() {
  const location = useLocation();
  useEffect(() => {
    const target = location.hash.replace('#', '');
    if (!target) return;
    const timer = window.setTimeout(() => scroller.scrollTo(target, { duration: 650, smooth: 'easeInOutQuart', offset: -90 }), 80);
    return () => window.clearTimeout(timer);
  }, [location.hash]);

  return <main className="overflow-hidden bg-[var(--bg-page)] pb-24 pt-24 sm:pt-28">
    <Hero/>
    <Element name="browse"><JourneySection id="browse" eyebrow="Discover" title="Browse Meals" description="HomeBite makes discovery feel simple, visual, and personal. Move from broad inspiration to the exact homemade dish you want." image={browseFood} imageAlt="Fresh healthy homemade meal"><motion.div initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.15 }} variants={{ hidden: {}, show: { transition: { staggerChildren: 0.07 } } }} className="grid gap-4 sm:grid-cols-2">{browseSteps.map((step, index) => <StepCard key={step.title} step={step} index={index}/>)}</motion.div><Link to="/foods" className="mt-8 inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-orange-500 to-rose-500 px-6 py-3.5 text-sm font-semibold text-white shadow-lg shadow-orange-500/20 focus:outline-none focus-visible:ring-4 focus-visible:ring-orange-500/30">Browse Meals <ArrowRight className="h-4 w-4"/></Link></JourneySection></Element>
    <Element name="order"><TimelineSection id="order" eyebrow="Checkout journey" title="Place Order" description="A clear, secure workflow takes you from selecting a meal to notifying the chef." steps={orderSteps}/></Element>
    <Element name="delivery"><JourneySection id="delivery" reverse eyebrow="After payment" title="Enjoy Homemade Food" description="Stay informed from chef acceptance to delivery, then share feedback with the community." image={deliveryFood} imageAlt="Traditional homemade meal ready to enjoy"><Timeline steps={deliverySteps}/><Link to="/dashboard/orders" className="mt-8 inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-orange-500 to-rose-500 px-6 py-3.5 text-sm font-semibold text-white shadow-lg shadow-orange-500/20 focus:outline-none focus-visible:ring-4 focus-visible:ring-orange-500/30">Track My Order <Truck className="h-4 w-4"/></Link></JourneySection></Element>
    <Benefits/>
    <Statistics/>
    <FAQ/>
    <FinalCTA/>
  </main>;
}

function Hero() { return <section className="relative isolate min-h-[680px] overflow-hidden border-b border-[var(--border)]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_20%,rgba(249,115,22,0.18),transparent_30%),radial-gradient(circle_at_85%_35%,rgba(139,92,246,0.16),transparent_28%)]"/><motion.div animate={{ y: [0, -20, 0], x: [0, 15, 0] }} transition={{ duration: 10, repeat: Infinity }} className="absolute -left-24 top-10 h-72 w-72 rounded-full bg-orange-500/10 blur-3xl"/><div className="container relative grid min-h-[680px] items-center gap-12 py-16 lg:grid-cols-[1fr_0.9fr]"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.65 }}><nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs font-semibold text-[var(--text-muted)]"><Link to="/" className="hover:text-[var(--accent)] focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-soft)]">Home</Link><span>/</span><span className="text-[var(--accent)]">How It Works</span></nav><p className="mt-10 text-sm font-bold uppercase tracking-[0.3em] text-[var(--accent)]">Your HomeBite journey</p><h1 className="mt-5 text-5xl font-semibold tracking-[-0.04em] text-[var(--text-primary)] sm:text-6xl lg:text-7xl">How HomeBite Works</h1><p className="mt-6 max-w-2xl text-base leading-8 text-[var(--text-secondary)] sm:text-lg">Discover authentic homemade meals, pay securely, follow every order update, and enjoy food prepared by trusted local chefs.</p><div className="mt-8 flex flex-wrap gap-3"><ScrollLink to="browse" smooth duration={650} offset={-90} className="cursor-pointer rounded-full bg-[var(--accent)] px-6 py-3.5 text-sm font-semibold text-white focus:outline-none focus-visible:ring-4 focus-visible:ring-[var(--accent-soft)]" tabIndex={0}>Start the journey</ScrollLink><Link to="/foods" className="rounded-full border border-[var(--border)] bg-[var(--bg-surface)] px-6 py-3.5 text-sm font-semibold text-[var(--text-primary)] focus:outline-none focus-visible:ring-4 focus-visible:ring-[var(--accent-soft)]">Explore meals</Link></div></motion.div><LazyImage src={heroFood} alt="A shared table filled with homemade meals" className="aspect-[4/3] w-full rounded-[2.5rem]" priority/></div></section>; }
function JourneySection({ id, eyebrow, title, description, image, imageAlt, reverse, children }) { return <section id={id} className="scroll-mt-28 border-b border-[var(--border)] py-24 sm:py-28"><div className={`container grid items-center gap-12 lg:grid-cols-2 ${reverse ? 'lg:[&>*:first-child]:order-2' : ''}`}><Reveal><LazyImage src={image} alt={imageAlt} className="aspect-[4/3] w-full rounded-[2.5rem]"/><div className="pointer-events-none absolute -bottom-6 -right-6 -z-10 h-40 w-40 rounded-full bg-[var(--accent-soft)] blur-2xl"/></Reveal><Reveal><p className="text-sm font-bold uppercase tracking-[0.3em] text-[var(--accent)]">{eyebrow}</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-[var(--text-primary)] sm:text-5xl">{title}</h2><p className="mt-5 text-base leading-8 text-[var(--text-secondary)]">{description}</p><div className="mt-8">{children}</div></Reveal></div></section>; }
function StepCard({ step, index }) { const Icon = step.icon; return <motion.article variants={{ hidden: { opacity: 0, y: 16 }, show: { opacity: 1, y: 0 } }} whileHover={{ y: -4 }} className="rounded-2xl border border-[var(--border)] bg-[var(--bg-surface)] p-4 shadow-lg shadow-black/5"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><Icon className="h-4 w-4"/></span><div><p className="text-[10px] font-bold uppercase tracking-wider text-[var(--text-muted)]">Step {index + 1}</p><h3 className="mt-1 text-sm font-semibold text-[var(--text-primary)]">{step.title}</h3><p className="mt-2 text-xs leading-5 text-[var(--text-secondary)]">{step.text}</p></div></div></motion.article>; }
function TimelineSection({ id, eyebrow, title, description, steps }) { return <section id={id} className="scroll-mt-28 border-b border-[var(--border)] bg-[var(--bg-muted)] py-24 sm:py-28"><div className="container"><Reveal className="mx-auto max-w-3xl text-center"><p className="text-sm font-bold uppercase tracking-[0.3em] text-[var(--accent)]">{eyebrow}</p><h2 className="mt-4 text-4xl font-semibold tracking-tight text-[var(--text-primary)] sm:text-5xl">{title}</h2><p className="mt-5 text-base leading-8 text-[var(--text-secondary)]">{description}</p></Reveal><div className="mx-auto mt-14 max-w-3xl"><Timeline steps={steps}/></div></div></section>; }
function Timeline({ steps }) { return <motion.div initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.12 }} variants={{ hidden: {}, show: { transition: { staggerChildren: 0.09 } } }} className="relative space-y-4 before:absolute before:bottom-8 before:left-6 before:top-8 before:w-px before:bg-[var(--border)]">{steps.map((step, index) => { const Icon = step.icon; return <motion.article key={step.title} variants={{ hidden: { opacity: 0, x: -18 }, show: { opacity: 1, x: 0 } }} className="relative flex gap-5 rounded-2xl border border-[var(--border)] bg-[var(--bg-surface)] p-4 shadow-lg shadow-black/5"><span className="relative z-10 flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-orange-500 to-rose-500 text-white shadow-lg shadow-orange-500/20"><Icon className="h-5 w-5"/></span><div className="pt-1"><p className="text-[10px] font-bold uppercase tracking-wider text-[var(--accent)]">{String(index + 1).padStart(2, '0')}</p><h3 className="mt-1 font-semibold text-[var(--text-primary)]">{step.title}</h3><p className="mt-1 text-sm leading-6 text-[var(--text-secondary)]">{step.text}</p></div></motion.article>; })}</motion.div>; }
function Benefits() { return <section className="border-b border-[var(--border)] py-24 sm:py-28"><div className="container"><Reveal className="mx-auto max-w-3xl text-center"><p className="text-sm font-bold uppercase tracking-[0.3em] text-[var(--accent)]">Built for trust</p><h2 className="mt-4 text-4xl font-semibold text-[var(--text-primary)] sm:text-5xl">Why Choose HomeBite</h2></Reveal><motion.div initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.12 }} variants={{ hidden: {}, show: { transition: { staggerChildren: 0.07 } } }} className="mt-14 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{benefits.map((item) => { const Icon = item.icon; return <motion.article key={item.title} variants={{ hidden: { opacity: 0, y: 18 }, show: { opacity: 1, y: 0 } }} whileHover={{ y: -5 }} className="rounded-[1.75rem] border border-[var(--border)] bg-[var(--bg-surface)] p-6 shadow-lg shadow-black/5"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><Icon className="h-5 w-5"/></span><h3 className="mt-5 text-lg font-semibold text-[var(--text-primary)]">{item.title}</h3><p className="mt-3 text-sm leading-7 text-[var(--text-secondary)]">{item.text}</p></motion.article>; })}</motion.div></div></section>; }
function Statistics() { const [ref, inView] = useInView({ triggerOnce: true, threshold: 0.25 }); const stats = [{ label: 'Meals Served', value: 12500, icon: UtensilsCrossed },{ label: 'Verified Chefs', value: 420, icon: ChefHat },{ label: 'Happy Customers', value: 8600, icon: Users },{ label: 'Orders Delivered', value: 10800, icon: Truck }]; return <section ref={ref} className="border-b border-[var(--border)] bg-[var(--bg-muted)] py-20"><div className="container grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat, index) => { const Icon = stat.icon; return <motion.article key={stat.label} initial={{ opacity: 0, y: 16 }} animate={inView ? { opacity: 1, y: 0 } : {}} transition={{ delay: index * 0.06 }} className="rounded-[1.75rem] border border-[var(--border)] bg-[var(--bg-surface)] p-6 text-center"><Icon className="mx-auto h-6 w-6 text-[var(--accent)]"/><p className="mt-4 text-4xl font-bold text-[var(--text-primary)]">{inView ? <CountUp end={stat.value} duration={2.2} separator="," suffix="+"/> : '0'}</p><p className="mt-2 text-sm text-[var(--text-muted)]">{stat.label}</p></motion.article>; })}</div></section>; }
function FAQ() { return <section className="border-b border-[var(--border)] py-24 sm:py-28"><div className="container max-w-4xl"><Reveal className="text-center"><p className="text-sm font-bold uppercase tracking-[0.3em] text-[var(--accent)]">Questions answered</p><h2 className="mt-4 text-4xl font-semibold text-[var(--text-primary)] sm:text-5xl">Frequently Asked Questions</h2></Reveal><Accordion allowZeroExpanded className="mt-12 space-y-4">{faqs.map((item, index) => <AccordionItem key={item.q} uuid={`how-${index}`} className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--bg-surface)]"><AccordionItemHeading><AccordionItemButton className="group flex w-full cursor-pointer items-center justify-between gap-4 px-5 py-5 text-left font-semibold text-[var(--text-primary)] outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[var(--accent)]">{item.q}<ChevronDown className="h-4 w-4 shrink-0 text-[var(--accent)] transition group-aria-expanded:rotate-180"/></AccordionItemButton></AccordionItemHeading><AccordionItemPanel className="px-5 pb-5 text-sm leading-7 text-[var(--text-secondary)]"><motion.p initial={{ opacity: 0, y: -4 }} animate={{ opacity: 1, y: 0 }}>{item.a}</motion.p></AccordionItemPanel></AccordionItem>)}</Accordion></div></section>; }
function FinalCTA() { return <section className="container py-24"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="relative overflow-hidden rounded-[2.5rem] bg-gradient-to-br from-slate-950 via-violet-950 to-orange-950 px-6 py-16 text-center text-white shadow-2xl sm:px-10"><div className="absolute -left-16 -top-24 h-72 w-72 rounded-full bg-orange-500/20 blur-3xl"/><div className="relative"><HeartHandshake className="mx-auto h-10 w-10 text-orange-300"/><h2 className="mt-6 text-3xl font-semibold text-white sm:text-5xl">Ready to Enjoy Homemade Meals?</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-white/70 sm:text-base">Find a local favorite, support talented home chefs, and bring something genuinely delicious to your table.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/foods" className="rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-violet-800 focus:outline-none focus-visible:ring-4 focus-visible:ring-white/30">Browse Meals</Link><Link to="/cook" className="rounded-full border border-white/20 bg-white/10 px-6 py-3.5 text-sm font-semibold text-white focus:outline-none focus-visible:ring-4 focus-visible:ring-white/30">Become a Chef</Link><Link to="/contact" className="rounded-full border border-white/20 px-6 py-3.5 text-sm font-semibold text-white focus:outline-none focus-visible:ring-4 focus-visible:ring-white/30">Contact Support</Link></div></div></motion.div></section>; }
function Reveal({ children, className = '' }) { const [ref, inView] = useInView({ triggerOnce: true, threshold: 0.15 }); return <motion.div ref={ref} initial={{ opacity: 0, y: 24 }} animate={inView ? { opacity: 1, y: 0 } : {}} transition={{ duration: 0.6 }} className={`relative ${className}`}>{children}</motion.div>; }
function LazyImage({ src, alt, className, priority }) { const [loaded, setLoaded] = useState(false); return <div className={`relative overflow-hidden bg-[var(--bg-muted)] shadow-[var(--shadow-elevated)] ${className}`}>{!loaded && <div className="absolute inset-0 animate-pulse bg-[var(--bg-muted)]" role="status" aria-label={`Loading ${alt}`}/>}<motion.img initial={{ opacity: 0 }} animate={{ opacity: loaded ? 1 : 0 }} transition={{ duration: 0.45 }} src={src} alt={alt} loading={priority ? 'eager' : 'lazy'} decoding="async" onLoad={() => setLoaded(true)} className="h-full w-full object-cover"/></div>; }
